### ISSUE TITLE
Redis Template brpop won't return after timeout when using jedis connection factory 

### ISSUE THREAD

**Issue by visdino** [spring-projects/spring-data-redis#1947] opened 2021-01-19 10:00 UTC
spring-data-redis version: 2.3.2.RELEASE
jedis-client version: 2.9.0

when there are multi threads executing brpop command at the same time, only one thread will get return after timeout.

**Comment by mp911de** [comment] 2021-01-19 10:17
That is likely a driver issue. Without further details, we're unable to investigate the issue.

If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by visdino** [comment] 2021-01-20 03:17
spring data redis: 2.3.2.RELEASE
jedis: 3.1.0
redis: 3.2.11

repo for reproduction: https://github.com/visdino/brpop

In this case, I start 3 threads to execute brpop commands after application started, with 5s timeout. 5s later, only one of these threads get return.

**Comment by mp911de** [comment] 2021-01-20 09:05
I'm not able to reproduce the reported issue. Removing Jedis and the pooling component works exactly the same as with Jedis and pooling:

```
2021-01-20T10:04:16.847052 : start brpop key : key2
2021-01-20T10:04:16.847052 : start brpop key : key0
2021-01-20T10:04:16.847080 : start brpop key : key1
2021-01-20T10:04:22.255785 : brpop timeout, key : key2 ,value : null
2021-01-20T10:04:22.255785 : brpop timeout, key : key0 ,value : null
2021-01-20T10:04:22.255775 : brpop timeout, key : key1 ,value : null
2021-01-20T10:04:22.255914 : start brpop key : key0
2021-01-20T10:04:22.255944 : start brpop key : key1
2021-01-20T10:04:22.255860 : start brpop key : key2
2021-01-20T10:04:27.374150 : brpop timeout, key : key0 ,value : null
2021-01-20T10:04:27.374192 : brpop timeout, key : key1 ,value : null
2021-01-20T10:04:27.374185 : brpop timeout, key : key2 ,value : null
2021-01-20T10:04:27.374332 : start brpop key : key1
2021-01-20T10:04:27.374369 : start brpop key : key2
2021-01-20T10:04:27.374255 : start brpop key : key0
2021-01-20T10:04:32.399976 : brpop timeout, key : key0 ,value : null
2021-01-20T10:04:32.399994 : brpop timeout, key : key2 ,value : null
2021-01-20T10:04:32.400004 : brpop timeout, key : key1 ,value : null
2021-01-20T10:04:32.400148 : start brpop key : key1
2021-01-20T10:04:32.400100 : start brpop key : key2
2021-01-20T10:04:32.400066 : start brpop key : key0
2021-01-20T10:04:37.421734 : brpop timeout, key : key0 ,value : null
2021-01-20T10:04:37.421827 : start brpop key : key0
2021-01-20T10:04:37.421832 : brpop timeout, key : key2 ,value : null
2021-01-20T10:04:37.422002 : start brpop key : key2
2021-01-20T10:04:37.421828 : brpop timeout, key : key1 ,value : null
2021-01-20T10:04:37.422106 : start brpop key : key1
2021-01-20T10:04:42.445987 : brpop timeout, key : key0 ,value : null
2021-01-20T10:04:42.445987 : brpop timeout, key : key1 ,value : null
2021-01-20T10:04:42.446054 : brpop timeout, key : key2 ,value : null
2021-01-20T10:04:42.446111 : start brpop key : key1
2021-01-20T10:04:42.446133 : start brpop key : key2
2021-01-20T10:04:42.446064 : start brpop key : key0
2021-01-20T10:04:47.465684 : brpop timeout, key : key2 ,value : null
2021-01-20T10:04:47.465706 : brpop timeout, key : key1 ,value : null
2021-01-20T10:04:47.465810 : start brpop key : key1
2021-01-20T10:04:47.465707 : brpop timeout, key : key0 ,value : null
2021-01-20T10:04:47.465770 : start brpop key : key2
2021-01-20T10:04:47.465888 : start brpop key : key0
```

Closing since this isn't a Spring Data issue.

**Closed by mp911de** 2021-01-20 09:05 UTC
Labels: status: feedback-provided
