### ISSUE TITLE
Add reactiveRepository

### ISSUE THREAD

**Issue by mollder** [spring-projects/spring-data-redis#2858] opened 2024-02-26 06:25 UTC
Hello, in the case of Redis, it is a common case to use it reactive, so I think providing a reactive repository is a good option, what do you think about this?

If it's okay, I'll look at the source code, refer to it, and then start adding a reactive repository

**Comment by mp911de** [comment] 2024-02-26 09:17
Duplicate of #1823

Thanks for reaching out. We do not intend to support reactive repositories.

**Closed by mp911de** 2024-02-26 09:17 UTC
Labels: status: duplicate

**Comment by mollder** [comment] 2024-02-27 07:36
thank you for your answer
