### ISSUE TITLE
ObjectHashMapper in Spring 2.5 - changed from storing as byte[] to storing as String

### ISSUE THREAD

**Issue by seleroy** [spring-projects/spring-data-redis#2193] opened 2021-11-04 18:48 UTC
Hello,
I upgraded from Spring 2.4.12 to Spring 2.5.4 and found a change of behaviour.
I have an object that I want to store using an hashmap, and not a json as json is not supported in GCP.

With the following config:
```
    @Bean
    public LettuceConnectionFactory redisConnectionFactory() {
        return new LettuceConnectionFactory();
    }

    @Bean
    public RedisTemplate<String,String> redisTemplate() {
        RedisTemplate<String,String> template = new RedisTemplate<>();
        template.setConnectionFactory(redisConnectionFactory());
        template.setKeySerializer(new StringRedisSerializer());
        template.setValueSerializer(new StringRedisSerializer());
        return template;
    }

```
With Spring 2.4, the following code was storing the Test object as a hash of byte[] in Redis:
```
private final HashOperations<String, byte[], byte[]> ops;
private final HashMapper<Object, byte[], byte[]> mapper;
public TestRepository(RedisTemplate<String, String> redisTemplate) {
        this.ops = redisTemplate.opsForHash();
        this.mapper = new ObjectHashMapper();
}
public void add(String key, Test test) {
        Map<byte[], byte[]> mappedHash = mapper.toHash(test);
        ops.putAll(key, mappedHash);
}
```

And the following code was retrieving a Test object correctly:

```
public Test  find(String key) {
        Map<byte[], byte[]> mappedHash = ops.entries(key);
        return (Test) mapper.fromHash(mappedHash);
```

When running the same code with Spring 2.5, the data are stored as String, and the fromHash methos now returns a ClassCastException complaining that a String cannot be cast to a [B]

What I am missing to make it work with Spring 2.5 ?

**Comment by christophstrobl** [comment] 2021-11-08 15:15
Thanks for reporting - To help us spot the issue please take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by spring-projects-issues** [comment] 2021-11-15 15:17
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-11-22 15:17
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-11-22 15:17 UTC
Labels: status: waiting-for-feedback, status: feedback-reminder
