### ISSUE TITLE
ID use  autoGenerate() but get the error: Invalid id format. Please use the 'millisecondsTime-sequenceNumber' format.

### ISSUE THREAD

**Issue by zhifliao** [spring-projects/spring-data-redis#2333] opened 2022-05-26 13:39 UTC
org.springframework.data.redis.RedisSystemException: Unknown redis exception; nested exception is java.lang.IllegalArgumentException: Invalid id format. Please use the 'millisecondsTime-sequenceNumber' format. at org.springframework.data.redis.FallbackExceptionTranslationStrategy.getFallback(FallbackExceptionTranslationStrategy.java:53) at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:43) at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:274) at org.springframework.data.redis.connection.lettuce.LettuceStreamCommands.convertLettuceAccessException(LettuceStreamCommands.java:721) at org.springframework.data.redis.connection.lettuce.LettuceStreamCommands.xReadGroup(LettuceStreamCommands.java:603) at org.springframework.data.redis.stream.DefaultStreamMessageListenerContainer.lambda$null$3(DefaultStreamMessageListenerContainer.java:259) at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:222) at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:189) at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:176) at org.springframework.data.redis.stream.DefaultStreamMessageListenerContainer.lambda$getReadFunction$4(DefaultStreamMessageListenerContainer.java:258) at org.springframework.data.redis.stream.StreamPollTask.readRecords(StreamPollTask.java:166) at org.springframework.data.redis.stream.StreamPollTask.doLoop(StreamPollTask.java:147) at org.springframework.data.redis.stream.StreamPollTask.run(StreamPollTask.java:132) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.IllegalArgumentException: Invalid id format. Please use the 'millisecondsTime-sequenceNumber' format. at org.springframework.util.Assert.isTrue(Assert.java:

**Comment by zhifliao** [comment] 2022-05-30 09:07
Environment: 5.04 version of redis, using the master/slave model, a total of 4 copies, 4 producers, 4 consumers. The average daily consumption messages is 60,000.

Subscriber code:
public class RedisStreamConfig {
    private static Logger logger = LoggerFactory.getLogger(RedisStreamConfig.class);

    @Autowired
    RedisSubscriber redisSubscriber;
    @Autowired
    RedisUtil redisUtil;
    @Autowired
    @Qualifier("streamExecutor")
    TaskExecutor taskExecutor;
    @Autowired
    RedisConfig redisConfig;

    @Bean
    public List<Subscription> subscription(RedisConnectionFactory factory) {
        List<Subscription> resultList = new ArrayList<>();
        StreamMessageListenerContainer.StreamMessageListenerContainerOptions<String, MapRecord<String, String, String>> options = StreamMessageListenerContainer
                .StreamMessageListenerContainerOptions
                .builder()
                .batchSize(100)
                .executor(taskExecutor)
                .errorHandler(e -> {
                    log.error("Error: ", e);
                })
                .pollTimeout(Duration.ofSeconds(1))
                .build();
        for (String redisStreamName : redisConfig.getStream()) {
            initStream(redisStreamName, redisConfig.getGroup());
            StreamMessageListenerContainer<String, MapRecord<String, String, String>> listenerContainer = StreamMessageListenerContainer.create(factory, options);
            Subscription subscription = listenerContainer.receiveAutoAck(Consumer.from(redisConfig.getGroup(), this.getClass().getName()),
                    StreamOffset.create(redisStreamName, ReadOffset.lastConsumed()), redisSubscriber);
            resultList.add(subscription);
            listenerContainer.start();
        }
        return resultList;
    }


    public void initStream(String key, String group) {
        logger.info("初始化stream:{},group:{}", key, group);
        boolean hasKey = redisUtil.hasKey(key);
        logger.info("stream:{},hasKey:{}", key, hasKey);
        if (!hasKey) {
            Map<String, Object> map = new HashMap<>();
            map.put("field", "value");
            RecordId recordId = redisUtil.addStream(key, map);
            redisUtil.addGroup(key, group);
        
            redisUtil.delField(key, recordId.getValue());
            logger.info("stream:{}-group:{} initialize success", key, group);
        }
    }

Consume code:
public class RedisSubscriber implements StreamListener<String, MapRecord<String, String, String>> {

    @Override
    public void onMessage(MapRecord<String, String, String> message) {
        logger.info("==========RecordId：{}", message.getId());
        String stream = message.getStream();
        long size = redisUtil.getSize(stream);
        if (size > redisConfig.getMaxQueue()) {
            long trimSize = redisUtil.trim(stream, redisConfig.getMaxQueue() / 2);  
        }       
    }
}

We printed out the error record id and found that the value was stream name：
![image](https://user-images.githubusercontent.com/33337907/170957849-b3cc144b-b4f6-494d-81fc-8fe966a14f3d.png)
but we pass the right id:
![672d21f4146c4b4444f6a22d6b151fd](https://user-images.githubusercontent.com/33337907/170957999-f1894f6e-8b3b-464f-bf26-503c62c131f0.png)

 thanks for replay!

**Comment by mp911de** [comment] 2022-06-02 07:20
I'm not able to reproduce the issue with the given code. Please provide a proper reproducer if you want us to diagnose the issue.

**Comment by spring-projects-issues** [comment] 2022-06-09 07:25
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-06-16 07:25
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-06-16 07:25 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, status: feedback-reminder
