### ISSUE TITLE
CRUD Repository findById or findAll methods always return Optional.empty (null) values.

### ISSUE THREAD

**Issue by Hitesh-Kirtane** [spring-projects/spring-data-redis#2130] opened 2021-07-21 15:30 UTC
**Hi Team,**

I am using Spring Boot 2.3.12.RELEASE with Spring Boot Starter Data Redis 2.3.12 which internally uses Spring Data Redis as a managed dependency.

When I am attempting to save an object using CRUD repository, I am able to save it without any error.

However, when I try to call findAll() or findById(Id) (here Id is the last inserted Id), I am always getting Optional.empty in the response from CRUD repository.

I have tried all the possible solutions available on the existing similar questions, but nothing seems to be working as of now.

Can you please check once and confirm what I have done wrong in the configurations or there is some other issue with the dependencies?

I have also posted this issue on StackOverFlow.

Here is the link to the issue posted on StackOverFlow on which you can find the code and the relevant screenshots.

https://stackoverflow.com/questions/68454213/spring-boot-redis-crud-repository-findbyid-or-findall-always-returns-optional-e

Thanks.

**Comment by mp911de** [comment] 2021-07-22 06:33
This is a duplicate of #2114.

**Closed by mp911de** 2021-07-22 06:33 UTC
Labels: status: duplicate

**Comment by Hitesh-Kirtane** [comment] 2021-07-23 20:30
**Hi Team,**

Issue #2114 is also unresolved and closed due to no feedback from the issuer of that ticket.

This issue has been marked as a duplicate of #2114, but there is no definite solution provided on the referenced issue as well.

It would be really helpful if you can at least post the solution for this issue before closing it.

Thanks.
