### ISSUE TITLE
`RedisSetCommands.isMember(K key, Object... objects)` throws `ClassCastException`

### ISSUE THREAD

**Issue by thanbv1510** [spring-projects/spring-data-redis#2759] opened 2023-11-01 17:32 UTC
- I use `Java 17` , `Redis Cluster version 7.0.10` and `spring-data-redis 3.1.2`
 - With the code that checks if a list of values ​​is in a set:
```java
var member = stringRedisTemplate.opsForSet().isMember("Blacklist[115]", "eeq7OACuw81wCrxqPICIWg==", "test2");
```
- I get this error:
```java
java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Boolean (java.lang.Long and java.lang.Boolean are in module java.base of loader 'bootstrap')

	at org.springframework.data.redis.core.DefaultSetOperations.lambda$isMember$10(DefaultSetOperations.java:169)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:406)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:373)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:97)
	at org.springframework.data.redis.core.DefaultSetOperations.isMember(DefaultSetOperations.java:158)
	at com.elcom.ads.contactcacher.ContactCacherApplicationTests.contextLoads(ContactCacherApplicationTests.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

- I reading source code and see error in line `isMember.put(objects[i], result.get(i));`
```java
        // in class src/main/java/org/springframework/data/redis/core/DefaultSetOperations.java
	@Override
	public Map<Object, Boolean> isMember(K key, Object... objects) {

		byte[] rawKey = rawKey(key);
		byte[][] rawValues = rawValues(objects);

		return execute(connection -> {

			List<Boolean> result = connection.sMIsMember(rawKey, rawValues);

			if (result == null || result.size() != objects.length) {
				return null;
			}

			Map<Object, Boolean> isMember = new LinkedHashMap<>(result.size());

			for (int i = 0; i < objects.length; i++) {
				isMember.put(objects[i], result.get(i)); 
			}

			return isMember;
		});
	}
```

**Comment by jxblum** [comment] 2023-11-01 23:33
Could you please create a simple test case reproducing the issue?

Spring Data Redis already contains a test case for `[Default]SetOperations.isMember(key, Object...)` method; see [here](https://github.com/spring-projects/spring-data-redis/blob/3.1.2/src/test/java/org/springframework/data/redis/core/DefaultSetOperationsIntegrationTests.java#L328-L345). This individual test case method tests for many different combinations of Redis driver [ _Jedis_, _Lettuce_ ] combined with different types for keys and values; see [here](https://github.com/spring-projects/spring-data-redis/blob/3.1.2/src/test/java/org/springframework/data/redis/core/AbstractOperationsTestParams.java#L50-L129).

The difference between Redis standalone and cluster should not matter in this case.

I distilled this down into a more directed test case matching your setup; see [here](https://github.com/jxblum/redis-experiments/blob/spring-data-redis-issue-2759/spring-data-redis-experiments/src/test/java/io/vmware/spring/data/redis/tests/commands/set/RedisSetOperationsIntegrationTests.java#L64-LL77).

All tests pass with _Jedis_ and _Lettuce_ in Spring Data Redis `3.1.2` as well as in the latest `3.1` release: `3.1.5`.

You cannot simply assume the `result.get(i)` invocation returns an numerical value simply because the Redis `SMISMEMBER` command ([doc](https://redis.io/commands/smismember/)) returns `1` if the value is a member of the targeted set and `0` if not.

You have to consider the return value from the underlying Redis driver API (_Jedis_ or _Lettuce_) used to invoke the set member command.

In the case of _Jedis_, Spring Data Redis [calls](https://github.com/spring-projects/spring-data-redis/blob/3.1.2/src/main/java/org/springframework/data/redis/connection/jedis/JedisSetCommands.java#L120) `Jedis::smismember`, which is [documented](https://www.javadoc.io/static/redis.clients/jedis/4.3.2/redis/clients/jedis/Jedis.html#smismember-byte:A-byte:A...-) to return a `List<Boolean>`.

Even if you are indirectly [calling](https://github.com/spring-projects/spring-data-redis/blob/3.1.2/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterSetCommands.java#L161) the SD Redis `JedisClusterSetCommands.sMIsMember(..)` method, this in turn invokes the Jedis drivers `JedisCluster.smismember(..)` method, which again returns a `List<Boolean>`; see [here](https://www.javadoc.io/static/redis.clients/jedis/4.3.2/redis/clients/jedis/UnifiedJedis.html#smismember-byte:A-byte:A...-).

In the case of _Lettuce_, Spring Data Redis simply [calls](https://github.com/spring-projects/spring-data-redis/blob/3.1.2/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceSetCommands.java#L120) _Lettuce's_ `RedisSetAsyncommands::smismember`, which, of course, returns a `List<Boolean>` as [documented](https://lettuce.io/core/release/api/io/lettuce/core/api/async/RedisSetAsyncCommands.html#smismember-K-V...-).

> NOTE: The `RedisFuture<List<Boolean>>` is properly handled and unwrapped by Spring Data Redis itself as a synchronous operations (i.e. waiting on the `Future`).

I wonder if you possibly altered your configuration in a non-prescribed, incompatible manner?

**Comment by JohnZYP** [comment] 2023-11-07 08:14
Please check if the Redisson dependency has been added. Remove it to resolve the issue, or alternatively, use Redisson's native API.

**Comment by thanbv1510** [comment] 2023-11-07 08:26
Yes, I using redisson with spring-data-redis, code correct if I remove redisson dependency

**Comment by jxblum** [comment] 2023-11-08 00:05
I can possibly [see](https://javadoc.io/static/org.redisson/redisson/3.24.3/org/redisson/client/protocol/RedisCommands.html#SMISMEMBER) how Redisson might have caused this problem `ClassCastException` being on your Spring (Data) application classpath, particularly if it somehow involved (used) the referenced `RedisCommand<List<Long>>` object.

Of course, this was not apparent from the provided Stack Trace above.

In general, Spring Data Redis does not integrate with any other library like Redisson, only other Spring libs (e.g. Spring Data Commons, the core Spring Framework, etc) and the Redis drivers (_Jedis_ and _Lettuce_) directly.

In particular, all integration of Redisson with Spring is handled by the Redisson project itself; see [Features](https://github.com/redisson/redisson#features), toward the bottom of the list.

I will be closing this ticket as `invalid` for now.

**Closed by jxblum** 2023-11-08 00:05 UTC
Labels: status: invalid

**Comment by mrniko** [comment] 2024-10-02 12:40
Fixed in https://github.com/redisson/redisson/issues/6209
