### ISSUE TITLE
Upgrade to Jedis 5.0

### ISSUE THREAD

**Issue by christophstrobl** [spring-projects/spring-data-redis#2612] opened 2023-06-15 05:31 UTC
Jedis 5 already released its [2nd beta](https://github.com/redis/jedis/releases/tag/v5.0.0-beta2) so we could follow along on current _main_ line till the GA is out.

**Comment by jxblum** [comment] 2023-06-16 02:26
I just did a quick stint on this, and upgrading Spring Data Redis to Jedis `5.0.0-beta2`, and it currently leads to the following compilation errors:

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisInvoker.java:[20,26] error: cannot find symbol
  symbol:   class Queable
  location: package redis.clients.jedis
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisInvoker.java:[1053,40] error: cannot find symbol
  symbol:   class Queable
  location: class JedisInvoker
[ERROR]   reason: class file for javax.annotation.meta.When not found
/Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterStreamCommands.java:[272,50] error: no suitable method found for xpending(byte[],byte[],byte[],byte[],int,byte[])
    method UnifiedJedis.xpending(String,String) is not applicable
      (actual and formal argument lists differ in length)
    method UnifiedJedis.xpending(String,String,XPendingParams) is not applicable
      (actual and formal argument lists differ in length)
    method UnifiedJedis.xpending(byte[],byte[]) is not applicable
      (actual and formal argument lists differ in length)
    method UnifiedJedis.xpending(byte[],byte[],XPendingParams) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterHashCommands.java:[163,73] error: incompatible types: List<Entry<byte[],byte[]>> cannot be converted to Map<byte[],byte[]>
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterHashCommands.java:[188,73] error: incompatible types: List<Entry<byte[],byte[]>> cannot be converted to Map<byte[],byte[]>
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterServerCommands.java:[253,100] error: incompatible types: bad return type in lambda expression
    Map<String,String> cannot be converted to List<String>
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterZSetCommands.java:[351,50] error: incompatible types: KeyValue<byte[],Tuple> cannot be converted to List<?>
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterZSetCommands.java:[392,50] error: incompatible types: KeyValue<byte[],Tuple> cannot be converted to List<?>
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterZSetCommands.java:[821,40] error: incompatible types: List<byte[]> cannot be converted to Set<byte[]>
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterZSetCommands.java:[838,77] error: incompatible types: List<Tuple> cannot be converted to Set<Tuple>
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterZSetCommands.java:[875,41] error: incompatible types: List<byte[]> cannot be converted to Set<byte[]>
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterZSetCommands.java:[892,78] error: incompatible types: List<Tuple> cannot be converted to Set<Tuple>
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterZSetCommands.java:[913,58] error: incompatible types: List<Tuple> cannot be converted to Set<Tuple>
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterZSetCommands.java:[974,41] error: incompatible types: List<byte[]> cannot be converted to Set<byte[]>
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterZSetCommands.java:[991,78] error: incompatible types: List<Tuple> cannot be converted to Set<Tuple>
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterZSetCommands.java:[1012,58] error: incompatible types: List<Tuple> cannot be converted to Set<Tuple>
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisConnection.java:[327,8] error: cannot find symbol
  symbol:   method quit()
  location: variable jedis of type Jedis
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisHashCommands.java:[125,39] error: cannot find symbol
  symbol:   method entrySet()
  location: variable it of type List<Entry<byte[],byte[]>>
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisHashCommands.java:[147,16] error: incompatible types: incompatible parameter types in lambda expression
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisZSetCommands.java:[328,9] error: incompatible types: invalid method reference
    incompatible types: KeyValue<byte[],Tuple> cannot be converted to List<?>
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisZSetCommands.java:[359,9] error: incompatible types: invalid method reference
    incompatible types: KeyValue<byte[],Tuple> cannot be converted to List<?>
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisZSetCommands.java:[427,33] error: incompatible types: inference variable R has incompatible bounds
    lower bounds: Set<byte[]>,Object
    lower bounds: List<byte[]>
  where R,T1 are type-variables:
    R extends Object declared in method <R,T1>just(ConnectionFunction1<T1,R>,PipelineFunction1<T1,R>,T1)
    T1 extends Object declared in method <R,T1>just(ConnectionFunction1<T1,R>,PipelineFunction1<T1,R>,T1)
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisZSetCommands.java:[453,33] error: incompatible types: inference variable R has incompatible bounds
    lower bounds: Set<byte[]>,Object
    lower bounds: List<byte[]>
  where R,T1,T2 are type-variables:
    R extends Object declared in method <R,T1,T2>just(ConnectionFunction2<T1,T2,R>,PipelineFunction2<T1,T2,R>,T1,T2)
    T1 extends Object declared in method <R,T1,T2>just(ConnectionFunction2<T1,T2,R>,PipelineFunction2<T1,T2,R>,T1,T2)
    T2 extends Object declared in method <R,T1,T2>just(ConnectionFunction2<T1,T2,R>,PipelineFunction2<T1,T2,R>,T1,T2)
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisZSetCommands.java:[507,33] error: incompatible types: inference variable R has incompatible bounds
    lower bounds: Set<byte[]>,Object
    lower bounds: List<byte[]>
  where R,T1,T2 are type-variables:
    R extends Object declared in method <R,T1,T2>just(ConnectionFunction2<T1,T2,R>,PipelineFunction2<T1,T2,R>,T1,T2)
    T1 extends Object declared in method <R,T1,T2>just(ConnectionFunction2<T1,T2,R>,PipelineFunction2<T1,T2,R>,T1,T2)
    T2 extends Object declared in method <R,T1,T2>just(ConnectionFunction2<T1,T2,R>,PipelineFunction2<T1,T2,R>,T1,T2)
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisConverters.java:[629,5] error: cannot find symbol
  symbol: method addParam(String)
[ERROR] /Users/jblum/pivdev/spring-data-redis/src/main/java/org/springframework/data/redis/connection/jedis/JedisConverters.java:[632,5] error: cannot find symbol
  symbol: method addParam(String)
[INFO] 26 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  25.974 s
[INFO] Finished at: 2023-06-15T19:18:43-07:00
[INFO] ------------------------------------------------------------------------
```

**Comment by vishalsingh2972** [comment] 2023-06-21 06:04
@christophstrobl can you assign this to me, want to give this a try!

**Comment by mp911de** [comment] 2023-07-11 13:54
Jedis 5 seems a major rewrite, judging from the amount of breaking changes: https://github.com/redis/jedis/releases/tag/v5.0.0-beta2

**Comment by lzysuqianqiu** [comment] 2023-09-04 02:39
Jedis 5.0 is GA now ,any progress?

**Comment by christophstrobl** [comment] 2023-09-04 07:18
@lzysuqianqiu the team is evaluating the impact associated to the quite extensive list of [breaking changes](https://github.com/redis/jedis/blob/master/docs/breaking-5.md).

**Comment by lzysuqianqiu** [comment] 2023-09-04 07:22
okay,get it

**Comment by jxblum** [comment] 2023-09-19 19:45
I have adapted SD Redis on the mainline ([issue/2612](https://github.com/spring-projects/spring-data-redis/tree/issue/2612) topic branch) to Jedis `5.0` API changes and all compilation issues have been resolved now.

However, there are still test failures (errors) in the Redis Pipelining and Transactional tests:

```txt
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   JedisClusterConnectionTests.bzPopMaxShouldWorkCorrectly:2309 » RedisSystem Unknown redis exception
[ERROR]   JedisClusterConnectionTests.bzPopMinShouldWorkCorrectly:2282 » RedisSystem Unknown redis exception
[ERROR]   JedisConnectionPipelineIntegrationTests>AbstractConnectionIntegrationTests.testZDiff:2039->AbstractConnectionPipelineIntegrationTests.verifyResults:175->AbstractConnectionPipelineIntegrationTests.getResults:189 » ClassCast class java.util.ArrayList cannot be cast to class java.util.Set (java.util.ArrayList and java.util.Set are in module java.base of loader 'bootstrap')
[ERROR]   JedisConnectionPipelineIntegrationTests>AbstractConnectionIntegrationTests.testZInter:2068->AbstractConnectionPipelineIntegrationTests.verifyResults:175->AbstractConnectionPipelineIntegrationTests.getResults:189 » ClassCast class java.util.ArrayList cannot be cast to class java.util.Set (java.util.ArrayList and java.util.Set are in module java.base of loader 'bootstrap')
[ERROR]   JedisConnectionPipelineIntegrationTests>AbstractConnectionIntegrationTests.testZInterAggWeights:2085->AbstractConnectionPipelineIntegrationTests.verifyResults:175->AbstractConnectionPipelineIntegrationTests.getResults:189 » ClassCast class java.util.ArrayList cannot be cast to class java.util.Set (java.util.ArrayList and java.util.Set are in module java.base of loader 'bootstrap')
[ERROR]   JedisConnectionPipelineIntegrationTests>AbstractConnectionIntegrationTests.testZUnion:2377->AbstractConnectionPipelineIntegrationTests.verifyResults:175->AbstractConnectionPipelineIntegrationTests.getResults:189 » ClassCast class java.util.ArrayList cannot be cast to class java.util.Set (java.util.ArrayList and java.util.Set are in module java.base of loader 'bootstrap')
[ERROR]   JedisConnectionPipelineIntegrationTests>AbstractConnectionIntegrationTests.testZUnionAggWeights:2394->AbstractConnectionPipelineIntegrationTests.verifyResults:175->AbstractConnectionPipelineIntegrationTests.getResults:189 » ClassCast class java.util.ArrayList cannot be cast to class java.util.Set (java.util.ArrayList and java.util.Set are in module java.base of loader 'bootstrap')
[ERROR]   JedisConnectionTransactionIntegrationTests>AbstractConnectionIntegrationTests.testZDiff:2039->AbstractConnectionTransactionIntegrationTests.verifyResults:175->AbstractConnectionTransactionIntegrationTests.getResults:165 » ClassCast class java.util.ArrayList cannot be cast to class java.util.Set (java.util.ArrayList and java.util.Set are in module java.base of loader 'bootstrap')
[ERROR]   JedisConnectionTransactionIntegrationTests>AbstractConnectionIntegrationTests.testZInter:2068->AbstractConnectionTransactionIntegrationTests.verifyResults:175->AbstractConnectionTransactionIntegrationTests.getResults:165 » ClassCast class java.util.ArrayList cannot be cast to class java.util.Set (java.util.ArrayList and java.util.Set are in module java.base of loader 'bootstrap')
[ERROR]   JedisConnectionTransactionIntegrationTests>AbstractConnectionIntegrationTests.testZInterAggWeights:2085->AbstractConnectionTransactionIntegrationTests.verifyResults:175->AbstractConnectionTransactionIntegrationTests.getResults:165 » ClassCast class java.util.ArrayList cannot be cast to class java.util.Set (java.util.ArrayList and java.util.Set are in module java.base of loader 'bootstrap')
[ERROR]   JedisConnectionTransactionIntegrationTests>AbstractConnectionIntegrationTests.testZUnion:2377->AbstractConnectionTransactionIntegrationTests.verifyResults:175->AbstractConnectionTransactionIntegrationTests.getResults:165 » ClassCast class java.util.ArrayList cannot be cast to class java.util.Set (java.util.ArrayList and java.util.Set are in module java.base of loader 'bootstrap')
[ERROR]   JedisConnectionTransactionIntegrationTests>AbstractConnectionIntegrationTests.testZUnionAggWeights:2394->AbstractConnectionTransactionIntegrationTests.verifyResults:175->AbstractConnectionTransactionIntegrationTests.getResults:165 » ClassCast class java.util.ArrayList cannot be cast to class java.util.Set (java.util.ArrayList and java.util.Set are in module java.base of loader 'bootstrap')
[ERROR] org.springframework.data.redis.core.DefaultStreamOperationsIntegrationTests.pendingShouldReadMessageDetails
[INFO]   Run 1: PASS
```

And:

```txt
[ERROR]   Run 10: DefaultStreamOperationsIntegrationTests.pendingShouldReadMessageDetails:409 » RedisSystem Unknown redis exception
[ERROR]   Run 11: DefaultStreamOperationsIntegrationTests.pendingShouldReadMessageDetails:409 » RedisSystem Unknown redis exception
[ERROR]   Run 12: DefaultStreamOperationsIntegrationTests.pendingShouldReadMessageDetails:409 » RedisSystem Unknown redis exception
[ERROR]   Run 13: DefaultStreamOperationsIntegrationTests.pendingShouldReadMessageDetails:409 » RedisSystem Unknown redis exception
[ERROR]   Run 14: DefaultStreamOperationsIntegrationTests.pendingShouldReadMessageDetails:409 » RedisSystem Unknown redis exception
[ERROR]   Run 15: DefaultStreamOperationsIntegrationTests.pendingShouldReadMessageDetails:409 » RedisSystem Unknown redis exception
[ERROR]   Run 16: DefaultStreamOperationsIntegrationTests.pendingShouldReadMessageDetails:409 » RedisSystem Unknown redis exception
[ERROR]   Run 17: DefaultStreamOperationsIntegrationTests.pendingShouldReadMessageDetails:409 » RedisSystem Unknown redis exception
[ERROR]   Run 18: DefaultStreamOperationsIntegrationTests.pendingShouldReadMessageDetails:409 » RedisSystem Unknown redis exception
```

I am currently trying to track the cause of these errors/failures down.

**Comment by jxblum** [comment] 2023-09-19 20:09
The SD Redis `JedisClusterConnectionTests.bzPopMaxShouldWorkCorrectly()` test case metho is currently erroring out due to a `NullPointerException` in the Jedis driver:

```txt
org.springframework.data.redis.RedisSystemException: Unknown redis exception

	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.getFallback(FallbackExceptionTranslationStrategy.java:49)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:39)
	at org.springframework.data.redis.connection.jedis.JedisClusterConnection.convertJedisAccessException(JedisClusterConnection.java:635)
	at org.springframework.data.redis.connection.jedis.JedisClusterZSetCommands.convertJedisAccessException(JedisClusterZSetCommands.java:1166)
	at org.springframework.data.redis.connection.jedis.JedisClusterZSetCommands.bZPopMax(JedisClusterZSetCommands.java:397)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.bZPopMax(DefaultedRedisConnection.java:1015)
	at org.springframework.data.redis.connection.jedis.JedisClusterConnectionTests.bzPopMaxShouldWorkCorrectly(JedisClusterConnectionTests.java:2309)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "l" is null
	at redis.clients.jedis.BuilderFactory$37.build(BuilderFactory.java:616)
	at redis.clients.jedis.BuilderFactory$37.build(BuilderFactory.java:611)
	at redis.clients.jedis.Connection.executeCommand(Connection.java:142)
	at redis.clients.jedis.executors.ClusterCommandExecutor.execute(ClusterCommandExecutor.java:139)
	at redis.clients.jedis.executors.ClusterCommandExecutor.executeCommand(ClusterCommandExecutor.java:93)
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:244)
	at redis.clients.jedis.UnifiedJedis.bzpopmax(UnifiedJedis.java:2360)
	at org.springframework.data.redis.connection.jedis.JedisClusterZSetCommands.bZPopMax(JedisClusterZSetCommands.java:395)
	... 5 more
```

**Comment by jxblum** [comment] 2023-09-19 20:11
The `JedisCusterConnectionTests.bzPopMinShouldWorkCorrectly()` test case method is failing for a similar reason:

```txt
org.springframework.data.redis.RedisSystemException: Unknown redis exception

	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.getFallback(FallbackExceptionTranslationStrategy.java:49)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:39)
	at org.springframework.data.redis.connection.jedis.JedisClusterConnection.convertJedisAccessException(JedisClusterConnection.java:635)
	at org.springframework.data.redis.connection.jedis.JedisClusterZSetCommands.convertJedisAccessException(JedisClusterZSetCommands.java:1166)
	at org.springframework.data.redis.connection.jedis.JedisClusterZSetCommands.bZPopMin(JedisClusterZSetCommands.java:356)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.bZPopMin(DefaultedRedisConnection.java:994)
	at org.springframework.data.redis.connection.jedis.JedisClusterConnectionTests.bzPopMinShouldWorkCorrectly(JedisClusterConnectionTests.java:2282)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "l" is null
	at redis.clients.jedis.BuilderFactory$37.build(BuilderFactory.java:616)
	at redis.clients.jedis.BuilderFactory$37.build(BuilderFactory.java:611)
	at redis.clients.jedis.Connection.executeCommand(Connection.java:142)
	at redis.clients.jedis.executors.ClusterCommandExecutor.execute(ClusterCommandExecutor.java:139)
	at redis.clients.jedis.executors.ClusterCommandExecutor.executeCommand(ClusterCommandExecutor.java:93)
	at redis.clients.jedis.UnifiedJedis.executeCommand(UnifiedJedis.java:244)
	at redis.clients.jedis.UnifiedJedis.bzpopmin(UnifiedJedis.java:2365)
	at org.springframework.data.redis.connection.jedis.JedisClusterZSetCommands.bZPopMin(JedisClusterZSetCommands.java:354)
	... 5 more
```

**Comment by jxblum** [comment] 2023-09-20 05:57
Both the `JedisConnectionPipelineIntegrationTests` and the `JedisConnectionTransactionIntegrationTests`: `testZDiff()`, `testZInter()`, `testZInterAggWeights()`, `testZUnion()` and `testZUnionAggWeights()` test case methods are failing due to a `ClassCastException`:

```txt
java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.util.Set (java.util.ArrayList and java.util.Set are in module java.base of loader 'bootstrap')

	at org.springframework.data.redis.connection.convert.SetConverter.convert(SetConverter.java:34)
	at org.springframework.data.redis.connection.DefaultStringRedisConnection.convertResults(DefaultStringRedisConnection.java:3084)
	at org.springframework.data.redis.connection.DefaultStringRedisConnection.closePipeline(DefaultStringRedisConnection.java:2456)
	at org.springframework.data.redis.connection.AbstractConnectionPipelineIntegrationTests.getResults(AbstractConnectionPipelineIntegrationTests.java:189)
	at org.springframework.data.redis.connection.AbstractConnectionPipelineIntegrationTests.verifyResults(AbstractConnectionPipelineIntegrationTests.java:175)
	at org.springframework.data.redis.connection.AbstractConnectionIntegrationTests.testZDiff(AbstractConnectionIntegrationTests.java:2039)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

Internally, when Jedis returns the "pipelined" (or transactional / "queued") results for the sorted set diff, interaction and union operations, it is returning an `ArrayList`, not a `Set`.

**Comment by mp911de** [comment] 2023-09-20 06:37
Previous versions had that kind of deviation as well. We then typically compensate for such differences via `fromMany(…).toList()/.toSet()` to be able to make progress.

**Comment by jxblum** [comment] 2023-09-20 16:11
It is technically more involved than that. 

When the Redis Pipeline is (finally) closed, the results are then converted, but are done so in the `DefaultStringRedisConnection`, which is a shared component between Jedis and Lettuce. Therefore, when you fix Jedis, you break Lettuce and vice versa.

You can see an early solution I was working on yesterday in my [cloned, alternative topic branch](https://github.com/jxblum/spring-data-redis/commits/issue/2612/jedis5.0-alt).

Obviously, this fixes Jedis, but breaks Lettuce! Technically, this re-breaks the non-Pipelined, non-Transactional Jedis tests, too. So, even Jedis is inconsistent in it's return values, where sorted set operations are concerned, at least.

> NOTE: As a side note, I have already observed several anomalies with the new Jedis driver, that are BUGS(!), IMO.

I also think part of the problem is that Spring Data Redis itself does not have a enough separation between Jedis and Lettuce, for example, `DefaultStringRedisConnection` and where `Converters` get applied. The "intermediate" results returned by the drivers are an "implementation" detail, yet get handled in `DefaultStringRedisConnection`, which is brittle at best given differences between Jedis and Lettuce in this regard.

I now need to reconsider where the changes need to (can) be applied to appease Jedis and not break Lettuce, which is a sure sign of a design issue in SDR.

**Comment by jxblum** [comment] 2023-09-20 22:34
Alright!

I have dwindle the Spring Data Redis build issues (compilation and tests) down to a single test case failure involving `JedisCluster`.

The `DefaultStreamOperationsIntegrationTests.pendingShouldReadMessageDetails()` test case method is failing for all (9) parameters (combinations) of `JedisCluster` connections with values `[ Strings, Longs, Doubles, bytes, Person, XStream**2, JSON**2 ]`, due to:

```txt
org.springframework.data.redis.RedisSystemException: Unknown redis exception

	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.getFallback(FallbackExceptionTranslationStrategy.java:49)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:39)
	at org.springframework.data.redis.connection.jedis.JedisClusterConnection.convertJedisAccessException(JedisClusterConnection.java:635)
	at org.springframework.data.redis.connection.jedis.JedisClusterStreamCommands.convertJedisAccessException(JedisClusterStreamCommands.java:399)
	at org.springframework.data.redis.connection.jedis.JedisClusterStreamCommands.xPending(JedisClusterStreamCommands.java:294)
	at org.springframework.data.redis.connection.DefaultedRedisConnection.xPending(DefaultedRedisConnection.java:580)
	at org.springframework.data.redis.connection.DefaultStringRedisConnection.xPending(DefaultStringRedisConnection.java:2993)
	at org.springframework.data.redis.connection.RedisStreamCommands.xPending(RedisStreamCommands.java:707)
	at org.springframework.data.redis.core.DefaultStreamOperations.lambda$pending$9(DefaultStreamOperations.java:205)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:406)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:373)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:97)
	at org.springframework.data.redis.core.DefaultStreamOperations.pending(DefaultStreamOperations.java:205)
	at org.springframework.data.redis.core.DefaultStreamOperationsIntegrationTests.pendingShouldReadMessageDetails(DefaultStreamOperationsIntegrationTests.java:410)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$15$1.accept(ReferencePipeline.java:541)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
....
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at redis.clients.jedis.StreamEntryID.<init>(StreamEntryID.java:24)
	at redis.clients.jedis.StreamEntryID.<init>(StreamEntryID.java:19)
	at org.springframework.data.redis.connection.jedis.JedisClusterStreamCommands.xPending(JedisClusterStreamCommands.java:283)
	... 64 more

```

**Comment by jxblum** [comment] 2023-09-20 23:04
Spring Data Redis to Jedis `5.0` upgrade complete!

**Comment by jxblum** [comment] 2023-09-26 21:22
Upgrading to Jedis `5.0.1`, which is now [available](https://central.sonatype.com/artifact/redis.clients/jedis/5.0.1).

**Closed** 2023-10-04 06:21 UTC
Labels: type: dependency-upgrade
