### ISSUE TITLE
Questions about execution performance

### ISSUE THREAD

**Issue by yuyu414** [spring-projects/spring-data-redis#2076] opened 2021-06-03 06:43 UTC
redis version：
![image](https://user-images.githubusercontent.com/25549434/120598876-5faa1100-c479-11eb-96b1-b86883ae6f4f.png)

user client version：spring-data-redis2.1.9release
config：
  spring.redis.database=XXX
  spring.redis.host=xxx
  spring.redis.port=xxx
  spring.redis.password=xxx
  spring.redis.timeout=PT10S
  spring.redis.jedis.pool.max-active=20
  spring.redis.jedis.pool.max-wait=-1ms
  spring.redis.jedis.pool.max-idle=5
  spring.redis.jedis.pool.min-idle=2
question:
When the data reaches 500,000, there will be obvious delay in the request (ten times difference). After deleting a part of the data, it returned to normal, using redis stand-alone version. Inside the intranet. After stress test, it was confirmed that redis server had no problem, which may be the problem of the client. Would you like to ask the possible reason? Or how to use it efficiently?

**Comment by yuyu414** [comment] 2021-06-03 06:45
There is no abnormality in redis server CPU and memory during pressure test

**Comment by mp911de** [comment] 2021-06-07 11:12
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem. Having at least a code sample that shows the usage where the reported issue arises would be helpful.

**Comment by yuyu414** [comment] 2021-06-08 01:56
> 如果您希望我们花些时间帮助您诊断问题，请花些时间描述它，最好是提供一个[最小样本](https://stackoverflow.com/help/mcve)这再现了问题。至少有一个代码示例来显示所报告问题出现的地方的用法将会很有帮助。

OK，
`    @Bean
    public RedisTemplate redisTemplate(RedisConnectionFactory redisConnectionFactory) {
        RedisTemplate redisTemplate = new RedisTemplate<>();
        redisTemplate.setConnectionFactory(redisConnectionFactory);

        // 设置键（key）的序列化采用StringRedisSerializer。
        redisTemplate.setKeySerializer(new StringRedisSerializer());
        // 设置值（value）的序列化采用FastJsonRedisSerializer。
        redisTemplate.setValueSerializer(new JdkSerializationRedisSerializer());

        redisTemplate.afterPropertiesSet();
        return redisTemplate;
    }
    @Autowired
    private StringRedisTemplate stringRedisTemplate;

   stringRedisTemplate.boundValueOps(key).set(value)
`
That's all

**Comment by mp911de** [comment] 2021-06-28 12:14
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by mp911de** 2021-06-28 12:14 UTC
Labels: status: feedback-provided, status: waiting-for-triage
