### ISSUE TITLE
Spring session data redis has issue when AWS Redis cluster upgrade version

### ISSUE THREAD

**Issue by pbluong** [spring-projects/spring-data-redis#2549] opened 2023-04-14 07:41 UTC
Version: `spring-session-data-redis-2.2.5.RELEASE`

In my application, I am using Jedis to connect to the Amazon Redis cluster. Everything went well until recently when AWS forced an upgrade of all the Redis server versions from `5.0.3` to `5.0.6`.

What we observed is that after the upgrade, the application still works without any restart. However, the `org.springframework.data.redis.connection.RedisConnectionCommands#ping` took much longer than normal. If we restart the application, the command `ping` is fast again.

We spent much time to analyze this issue because it was a big issue in our application. In the analysis, we found that the issue comes from the `org.springframework.data.redis.connection.jedis.JedisClusterConnection.JedisClusterTopologyProvider#getTopology(..)` method when upgrading Redis version (we don't know exactly what Amazon did), but we can see that it created new cluster with new IP addresses and its slaves. The old nodes from the old cluster are cached but they were no longer available. The current logic `shuffles` the list, then loops over the list and tries to reach the node. So, if the invalid nodes are at the beginning of the list, it will take time to reach the valid node(s). It explains why the `ping` command is randomly slow & fast. It depends on the `shuffle` method.

![image](https://user-images.githubusercontent.com/4244403/231977289-d971a9df-66d6-485d-81a6-4b8531fd4a59.png)

![image](https://user-images.githubusercontent.com/4244403/231977408-8a90ed12-41b2-468b-8361-a9dd9d43ae5c.png)

It would be great if the team could have a look and see if it is really a bug?

Thanks and best regards

**Comment by jxblum** [comment] 2023-05-08 04:56
First, a bit of feedback...

Spring Data Redis `2.2.x` (an in particular `2.2.5-RELEASE`) has been out of OSS support since September 20th, 2020 (see [support timelines](https://spring.io/projects/spring-data-redis#support) for more details). 

Furthermore, it is not even possible to buy "commercial support" (with a valid [VMware Spring Runtime](https://tanzu.vmware.com/spring-runtime) license) unless you were running Spring Data Redis `2.5.x`, which will end in August 2023.

Additionally, you are encouraged to always use the latest service release (patch release) of any Spring Data Redis `major.minor` version, such as the version you are currently on,`2.2`, which would be `2.2.13-RELEASE` ([here](https://github.com/spring-projects/spring-data-redis/tree/2.2.13.RELEASE)). There is very little to no risk in using the latest service/patch release of any Spring Data Redis `major.minor` version.

I would even highly recommend moving to Spring Data Redis `2.7` as soon as possible, and even consider moving to Spring Data Redis `3.0` (`3.0.5` is the latest service/patch release version in `3.0.x` already). 

The only caveat by moving to SD Redis `3.0` is that it minimally requires Java 17, Jakarta EE 9/10, and is based on Spring Framework `6.0`.

Note that, even though Spring Data Redis 2.7 OSS support states it expires this month, May 2023, it is possible that `2.7` will get extended until November 2023 to allow users more time to transition from the `2.x` Java 8 baseline to the `3.x` Java 17 baseline. The reason I say this is, Spring Boot `2.7.x` OSS support was originally going to end this May 2023, but has be pushed out to November 2023 (see [here](https://spring.io/projects/spring-boot#support)). We typically, though not always, follow Spring Boots support timelines.

I am actually requesting clarification on this during tomorrow's Spring Data team meeting.

**Comment by jxblum** [comment] 2023-05-08 05:12
Having stated the above...

We, the Spring Data team, are actually performing 1 final release of Spring Data Redis `2.7.x` (which will be SD Redis `2.7.12`) tentatively [scheduled](https://calendar.spring.io/) on Friday, May 12th, 2023.

Of course, this may change if the Spring Data Redis `2.7.x` OSS support timeline is pushed out to November 2023 to match Spring Boot `2.7.x`. However, I need to confirm this first.

**Comment by jxblum** [comment] 2023-05-08 05:19
It would appear that this problem inside AWS would still be a problem today, even for Spring Data Redis `3.x` and beyond (see [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterConnection.java#L829-L830)).

Ironically, the `Collections.shuffle(list)` call on line `830` is completely arbitrary and quite likely unnecessary. However, it looks like it was a [contribution submitted by a user](https://github.com/spring-projects/spring-data-redis/blame/3.0.5/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterConnection.java#L830) on November 18th, 2018, related to DATAREDIS-890, with details:

```
DATAREDIS-890 - Randomize Redis Cluster node order before topology retrieval.

We now shuffle the set of Redis Cluster nodes before retrieving the topology. This change reduces load on the first node in the known nodes set.

Original pull request: #373.
```

DATAREDIS-890 (from our now retired Spring JIRA Issue tracker) corresponds to Issue #1427.

**Comment by jxblum** [comment] 2023-05-08 06:56
I was actually wondering whether there is a more intelligent way to "order" the `List` ([here](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterConnection.java#L829)), such as such that more recent nodes could/would be stored in the beginning of the `List`.

This would require us to know exactly what kind of `redis.clients.jedis.ConnectionPool` the Jedis driver's, `redis.clients.jedis.JedisCluster.getTopology()` method returns? Unfortunately, the [Javadoc](https://www.javadoc.io/static/redis.clients/jedis/5.0.0-alpha1/redis/clients/jedis/JedisCluster.html#getClusterNodes--) is less than helpful.

The [Javadoc](https://www.javadoc.io/static/redis.clients/jedis/5.0.0-alpha1/redis/clients/jedis/ConnectionPool.html) for the Jedis `ConnectionPool` and `Connection` ([Javadoc](https://www.javadoc.io/static/redis.clients/jedis/5.0.0-alpha1/redis/clients/jedis/Connection.html)) are equally worthless. 

If there were some kind of metadata on the `Connection` itself that would help with this "smart" ordering, then that might be beneficial. But, in the source for `Connection` as determined by the SD Redis dependency, I see...

```java
package redis.clients.jedis;

import ...;

public class Connection implements Closeable {

  private ConnectionPool memberOf;
  private final JedisSocketFactory socketFactory;
  private Socket socket;
  private RedisOutputStream outputStream;
  private RedisInputStream inputStream;
  private int soTimeout = 0;
  private int infiniteSoTimeout = 0;
  private boolean broken = false;

// ...
```

Which is not all that helpful in this case.

However, I am curious about 2 things.

1) First, let's assume the `JedisCluster.getTopology()` only returns valid, "active" `Connections` that produce an immediate response (for example, on `ping`). Then perhaps the problem is not with the `Connections` but with the "cached" topology returned by SD Redis's `JedisClusterTopologyProvider`, [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterConnection.java#L823-L825).

This "cached" topology will [expire](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterConnection.java#L823) (i.e. `shouldUseCachedValue`) as defined [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterConnection.java#L868)) after a set, [configurable](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterConnection.java#L810) timeout (i.e. `cacheTimeMs`), which [defaults to 100ms](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterConnection.java#L799-L800).

100 milliseconds could prove quite detrimental in a really large cluster (100s or 1000s of nodes, depending on your scale).

So, you could try this in configuration...

```java
@Configuration
class MySpringDataRedisApplicationConfiguration {

  @Bean
  JedisConnectionFactory customJedisConnectionFactory(JedisClientConfiguration clientConfiguration, 
      RedisClusterConfiguration clusterConfiguration) {

    return new JedisConnectionFactory(clusterConfiguration, clientConfiguration) {

      @Override
      protected ClusterTopologyProvider createTopologyProvider(JedisCluster cluster) {

        // NOTE: I arbitrarily specified a `Duration` in nanoseconds, but you should determine 
        // the correct `Duration` for your application use case, inside AWS!

        return new new JedisClusterTopologyProvider(cluster, Duration.ofNanos(50));
      }
    };
  }
}
```

2) Alternatively, you might want to consider changing the `SO_TIMEOUT` of the actual `Sockets` used by the Jedis (Cluster) `Connections` used to issue Redis commands, such as `ping`. As you can see in the Jedis `Connection` class definition I showed above (from source), the `soTimeout` defaults to `0`. And, as the [Javadoc](https://docs.oracle.com/javase/8/docs/api/java/net/Socket.html#setSoTimeout-int-) for `java.net.Socket.setSoTimeout(:int) states:

> "_A timeout of zero is interpreted as an infinite timeout._"

An "infinite timeout" is probably not what you are after either, especially if the node is non-responsive or not longer available since AWS recycled the IP addresses for the new nodes in the new cluster.

You should be able to accomplish this with the following code:

```java
@Configuration
class MySpringDataRedisApplicationConfiguration {

  @Bean
  JedisClientConfiguration customJedisClientConfiguration() {

    // NOTE: Once again, I chose an arbitrary `Duration`; you must decide what is best for your application!

    // NOTE: I set both `connect` and `read` timeouts, here, incase the node exists, but become unresponsive!

    return JedisClientConfiguration.builder()
      .connectTimeout(Duration.ofNanos(50))
      .readTime(Duration.ofNanos(50))
      .build();
  }
}
```

> DISCLAIMER: I wrote the code from scratch (and memory) so I apologize for any syntax errors in advance. But hopefully you will get the idea.

The SD Redis `JedisClientConfiguration` get converted into a Jedis driver API `JedisClientConfig` [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/connection/jedis/JedisConnectionFactory.java#L315-L340).

Please try either (or both, and perhaps together) of these 2 options and let me know your results.

I will leave this ticket open for the time being, but I am not convinced that Spring Data Redis needs to be changed yet.

Thank you and good luck!

**Comment by jxblum** [comment] 2023-05-08 18:21
1 last bit of feedback here, you might want to consider trying the [Lettuce Redis (client) driver](https://lettuce.io/) instead of **Jedis** if you continue to have problems, even after my suggestions [above](https://github.com/spring-projects/spring-data-redis/issues/2549#issuecomment-1537848142).

**Closed as not planned** 2023-05-22 18:28 UTC
Labels: for: external-project, in: core, in: jedis
