### ISSUE TITLE
Redis command timed out [DATAREDIS-1255]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1809] opened 2020-11-19 03:20 UTC
**[wangwei91](https://jira.spring.io/secure/ViewProfile.jspa?name=JIRAUSER50693)** opened **[DATAREDIS-1255](https://jira.spring.io/browse/DATAREDIS-1255?redirect=false)** and commented

Hello, I am using redis stream. When I listen on the client, the lettuce connection will be disconnected. How can I keep listening continuously

error message:

```
org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 2 second(s)org.springframework.dao.QueryTimeoutException: Redis command timed out; nested exception is io.lettuce.core.RedisCommandTimeoutException: Command timed out after 2 second(s) at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:70) at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41) at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44) at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42) at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:273) at org.springframework.data.redis.connection.lettuce.LettuceStreamCommands.convertLettuceAccessException(LettuceStreamCommands.java:712) at org.springframework.data.redis.connection.lettuce.LettuceStreamCommands.xReadGroup(LettuceStreamCommands.java:620) at org.springframework.data.redis.connection.DefaultedRedisConnection.xReadGroup(DefaultedRedisConnection.java:591) at org.springframework.data.redis.core.DefaultStreamOperations$4.inRedis(DefaultStreamOperations.java:310) at org.springframework.data.redis.core.DefaultStreamOperations$RecordDeserializingRedisCallback.doInRedis(DefaultStreamOperations.java:376) at org.springframework.data.redis.core.DefaultStreamOperations$RecordDeserializingRedisCallback.doInRedis(DefaultStreamOperations.java:371) at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:228) at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:188) at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:96) at org.springframework.data.redis.core.DefaultStreamOperations.read(DefaultStreamOperations.java:305) at org.springframework.data.redis.stream.DefaultStreamMessageListenerContainer.lambda$getReadFunction$3(DefaultStreamMessageListenerContainer.java:236) at org.springframework.data.redis.stream.StreamPollTask.doLoop(StreamPollTask.java:138) at org.springframework.data.redis.stream.StreamPollTask.run(StreamPollTask.java:123) at com.fosafer.config.AsyncTaskExecutorExtend.lambda$createWrappedRunnable$1(AsyncTaskExecutorExtend.java:76) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:748)Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 2 second(s) at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51) at io.lettuce.core.LettuceFutures.awaitOrCancel(LettuceFutures.java:119) at io.lettuce.core.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:75) at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:79) at com.sun.proxy.$Proxy155.xreadgroup(Unknown Source) at org.springframework.data.redis.connection.lettuce.LettuceStreamCommands.xReadGroup(LettuceStreamCommands.java:618) ... 15 more
```

code:

```java
public class StreamConsumerRunner implements ApplicationRunner,DisposableBean {

 @Autowired
 RedisConnectionFactory redisConnectionFactory;

 @Autowired
 RedisTemplate objectRedisTemplate;

 @Resource
 AsyncTaskExecutorExtend taskExecutor;

 @Autowired
 Jackson2JsonRedisSerializer jackson2JsonRedisSerializer;

 @Autowired
 StringRedisSerializer stringRedisSerializer;

 @Autowired
 StreamMessageListener streamMessageListener;

 private StreamMessageListenerContainer<String, MapRecord<String, String, Object>> streamMessageListenerContainer;
 @Override
 public void run(ApplicationArguments args) throws Exception {
 StreamInfo.XInfoGroups groups = objectRedisTemplate.opsForStream().groups("testMap");
 Set<String> groupSet = new HashSet<>();
 groups.forEach(xInfoGroup -> {
 groupSet.add(xInfoGroup.groupName());
 });
 if(!groupSet.contains("group-1")){
 objectRedisTemplate.opsForStream().createGroup("testMap","group-1");
 }
 StreamMessageListenerContainer.StreamMessageListenerContainerOptions streamMessageListenerContainerOptions = StreamMessageListenerContainer.StreamMessageListenerContainerOptions
 .builder()
 .batchSize(10)
 .executor(this.taskExecutor)
 .errorHandler(new ErrorHandler() {
 @Override
 public void handleError(Throwable throwable) {
 // throw new RuntimeException(t);
 throwable.printStackTrace();
 }
 })
 .pollTimeout(Duration.ZERO)
 .keySerializer(stringRedisSerializer)
 .hashKeySerializer(stringRedisSerializer)
 .hashValueSerializer(jackson2JsonRedisSerializer)
 .build();
 StreamMessageListenerContainer streamMessageListenerContainer = StreamMessageListenerContainer
 .create(this.redisConnectionFactory, streamMessageListenerContainerOptions);

 streamMessageListenerContainer.receive(Consumer.from("group-1", "consumer-1"),
 StreamOffset.create("testMap", ReadOffset.lastConsumed()), this.streamMessageListener);

 this.streamMessageListenerContainer = streamMessageListenerContainer;
 this.streamMessageListenerContainer.start();
 }
 @Override
 public void destroy() throws Exception {
 this.streamMessageListenerContainer.stop();
 }
}
```

---

**Affects:** 2.3.5 (Neumann SR5)

**Comment by mp911de** [comment] 2021-06-28 12:28
Closing since we cannot reproduce the issue.

**Closed by mp911de** 2021-06-28 12:28 UTC
Labels: status: invalid

**Comment by SCLogo** [comment] 2022-04-13 08:49
@spring-projects-issues did you find the root cause of your problem ?
