### ISSUE TITLE
RedisSerializer question

### ISSUE THREAD

**Issue by mingtiao13** [spring-projects/spring-data-redis#2192] opened 2021-11-03 09:27 UTC
When using RedisTemplate in the project, it is possible to specify the serialization method of redis, and it is also recommended to use a custom serialization method.We are now using Jackson2JsonRedisSerializer, but when using StreamMessageListenerContainer, a DefaultStreamMessageListenerContainer is used. The serialization method is different from the one I configured, how should I modify it?

    @Bean
    public Subscription subscription(RedisConnectionFactory factory) {
        Jackson2JsonRedisSerializer<Object> jackson2JsonRedisSerializer = new Jackson2JsonRedisSerializer<>(Object.class);
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.setVisibility(PropertyAccessor.ALL, JsonAutoDetect.Visibility.ANY);

        objectMapper.activateDefaultTyping(LaissezFaireSubTypeValidator.instance, ObjectMapper.DefaultTyping.NON_FINAL);

        objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        objectMapper.registerModule(new JavaTimeModule());
        objectMapper.activateDefaultTypingAsProperty(LaissezFaireSubTypeValidator.instance,
                ObjectMapper.DefaultTyping.NON_FINAL, String.valueOf(JsonTypeInfo.As.PROPERTY));
        jackson2JsonRedisSerializer.setObjectMapper(objectMapper);

        StreamMessageListenerContainer.StreamMessageListenerContainerOptions<String, ObjectRecord<String, RedisStreamMessage>> options = StreamMessageListenerContainer
                .StreamMessageListenerContainerOptions
                .builder()
                .keySerializer(new StringRedisSerializer())
                .hashKeySerializer(jackson2JsonRedisSerializer)
                .hashValueSerializer(jackson2JsonRedisSerializer)
                .pollTimeout(Duration.ofSeconds(1))
                .targetType(RedisStreamMessage.class)
                .build();
        StreamMessageListenerContainer<String, ObjectRecord<String, RedisStreamMessage>> listenerContainer = StreamMessageListenerContainer.create(factory, options);
        var subscription =  listenerContainer.receiveAutoAck(
                Consumer.from(RedisStreamConstant.STREAM_GROUP, "localhost"),
                StreamOffset.create(RedisStreamConstant.STREAM_KEY, ReadOffset.lastConsumed()),
                streamListener);
        listenerContainer.start();
        return subscription;
    }

    @Bean
    public RedisTemplate<String, Object> redisTemplate(RedisConnectionFactory redisConnectionFactory) {
        RedisTemplate<String, Object> redisTemplate = new RedisTemplate<>();
        redisTemplate.setConnectionFactory(redisConnectionFactory);

        Jackson2JsonRedisSerializer<Object> jackson2JsonRedisSerializer = new Jackson2JsonRedisSerializer<>(Object.class);
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.setVisibility(PropertyAccessor.ALL, JsonAutoDetect.Visibility.ANY);

        objectMapper.activateDefaultTyping(LaissezFaireSubTypeValidator.instance, ObjectMapper.DefaultTyping.NON_FINAL);

        objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        objectMapper.registerModule(new JavaTimeModule());
        objectMapper.activateDefaultTypingAsProperty(LaissezFaireSubTypeValidator.instance,
                ObjectMapper.DefaultTyping.NON_FINAL, String.valueOf(JsonTypeInfo.As.PROPERTY));
        jackson2JsonRedisSerializer.setObjectMapper(objectMapper);

        redisTemplate.setValueSerializer(new StringRedisSerializer());
        redisTemplate.setKeySerializer(new StringRedisSerializer());
        redisTemplate.setHashKeySerializer(jackson2JsonRedisSerializer);
        redisTemplate.setHashValueSerializer(jackson2JsonRedisSerializer);
        redisTemplate.afterPropertiesSet();
        return redisTemplate;
    }

```
   public Message<Object> testRedisStream() {
          RedisStreamMessage product = RedisStreamMessage.builder().type(2).build();
          ObjectRecord<String, RedisStreamMessage> record = StreamRecords.newRecord()
                  .ofObject(product)
                  .withStreamKey("run:js");
         redisTemplate.srAdd(record);
          return MsgResponseUtil.success();
   }

```
at error
```
org.springframework.core.convert.ConversionFailedException: Failed to convert from type [org.springframework.data.redis.connection.stream.StreamRecords$ByteMapBackedRecord] to type [com.zkpsych.common.entity.RedisStreamMessage] for value 'MapBackedRecord{recordId=1635931215830-0, kvMap={[B@56ad47c3=[B@3d5b2db9, [B@4219078f=[B@5a3c372f}}'; nested exception is java.lang.IllegalArgumentException: Value must not be null!
	at org.springframework.data.redis.stream.StreamPollTask.convertRecord(StreamPollTask.java:198)
	at org.springframework.data.redis.stream.StreamPollTask.deserializeAndEmitRecords(StreamPollTask.java:176)
	at org.springframework.data.redis.stream.StreamPollTask.doLoop(StreamPollTask.java:148)
	at org.springframework.data.redis.stream.StreamPollTask.run(StreamPollTask.java:132)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Value must not be null!
	at org.springframework.util.Assert.notNull(Assert.java:201)
	at org.springframework.data.redis.connection.stream.Record.of(Record.java:81)
	at org.springframework.data.redis.connection.stream.MapRecord.toObjectRecord(MapRecord.java:147)
	at org.springframework.data.redis.core.StreamObjectMapper.toObjectRecord(StreamObjectMapper.java:138)
	at org.springframework.data.redis.core.StreamOperations.map(StreamOperations.java:577)
	at org.springframework.data.redis.stream.DefaultStreamMessageListenerContainer.lambda$getDeserializer$2(DefaultStreamMessageListenerContainer.java:240)
	at org.springframework.data.redis.stream.StreamPollTask.convertRecord(StreamPollTask.java:196)
	... 4 common frames omitted

```

I noticed that you use the same method when serializing key and value. Do you suggest this?

	private RedisTemplate<K, V> createRedisTemplate(RedisConnectionFactory connectionFactory,
			StreamMessageListenerContainerOptions<K, V> containerOptions) {

		RedisTemplate<K, V> template = new RedisTemplate<>();
		template.setKeySerializer(containerOptions.getKeySerializer());
		template.setValueSerializer(containerOptions.getKeySerializer());
		template.setHashKeySerializer(containerOptions.getHashKeySerializer());
		template.setHashValueSerializer(containerOptions.getHashValueSerializer());
		template.setConnectionFactory(connectionFactory);
		template.afterPropertiesSet();

		return template;
	}

**Comment by christophstrobl** [comment] 2021-11-08 15:22
If you'd like us to spend some time investigating, please take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.

**Comment by spring-projects-issues** [comment] 2021-11-15 15:22
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-11-22 15:22
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-11-22 15:22 UTC
Labels: status: waiting-for-feedback, status: feedback-reminder
