### ISSUE TITLE
spring-data-redis 的 RedisTemplate 有两个bug

### ISSUE THREAD

**Issue by mobile664042** [spring-projects/spring-data-redis#2139] opened 2021-08-05 11:52 UTC
使用版本：spring-data-redis-2.1.18.RELEASE.jar

bug1. 自定义Bean的名称不能是redisTemplate(我本地使用是的com.xdd.redis.cluster.service.RedisTemplate会报错)； 启动的时候会根据beanName查到org.springframework.data.redis.core.RedisTemplate, 不然会报Cannot convert value of type 'com.xdd.redis.cluster.service.RedisTemplate' to required type 'org.springframework.data.redis.core.RedisOperations': no matching editors or conversion strategy found错误。

bug2.  org.springframework.data.redis.core.RedisKeyValueAdapter.initMessageListenerContainer()方法内部使用org.springframework.data.redis.core.RedisTemplate对RedisOperations<?, ?> redisOps强制转换，这种设计是不对，RedisOperations可能会有多个实现，不然会报错ClassCastException
![image](https://user-images.githubusercontent.com/1433479/128345069-6113b868-97d5-448d-b870-6a8545889643.png)

还有，朋友说在大并发场景下，会出现链接不释放，然后redis链接耗尽的问题，所有不改用你们的集群模式，改用原生的redis.clients.jedis.JedisCluster, 能否统一改改？

![image](https://user-images.githubusercontent.com/1433479/128345163-f2367ec2-3114-49e8-83c8-ecc93c2cf8e7.png)

**Comment by christophstrobl** [comment] 2021-08-05 12:05
Please report issues in `English` and use Markdown code fences ``` in case you need to add code snippets. Try to provide as much information as possible, ideally a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem.
Thank you.

**Comment by spring-projects-issues** [comment] 2021-08-12 12:08
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by mobile664042** [comment] 2021-08-19 02:43
> lease provide the requested information. If the

My English is bad. I just want to ask some question or there bug will be fixed ?

**Comment by mp911de** [comment] 2021-08-23 08:20
@mobile664042 without us being able to understand what problem you face, we cannot really do anything here. Google translate reports a translation that doesn't make any sense at all.

**Comment by spring-projects-issues** [comment] 2021-08-30 08:23
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2021-09-06 08:23
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2021-09-06 08:23 UTC
Labels: status: waiting-for-feedback, status: feedback-reminder, status: feedback-provided
