### ISSUE TITLE
Could not resolve subtype of simple type with spring-data-redis verison > 2.6.4

### ISSUE THREAD

**Issue by mamtananavati** [spring-projects/spring-data-redis#2401] opened 2022-09-06 23:47 UTC
Below is the stacktrace seen after bumping up spring-data-redis version to 2.7.2

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pipelineConfigUpdateManager': Invocation of init method failed; nested exception is org.springframework.data.redis.serializer.SerializationException: Could not read JSON: Could not resolve subtype of [simple type, class com.aw.dpa.common.pipeline.config.EntityConfig]: missing type id property '@class' (for POJO property 'entities')`

Here's what the code looks like 
`@Component("pipelineConfigUpdateManager")
class PipelineConfigUpdateManager implements ApplicationListener<PipelineConfigUpdateEvent> { 
    private final DistributableMap<String, LinkedHashSet<IntegrationConfig>> redisConfigsCache;
`
`public final class IntegrationConfig implements Serializable {
    private static final long serialVersionUID = 1L;
    @NotBlank
    @Pattern(
        regexp = "^[a-z][a-z0-9_]{0,63}+$"
    )
    private final String name;
    @Valid
    private final List<EntityConfig> entities;
`

This serialization issue starts with the anything beyond   2.6.4 and spring boot > 2.6
This issue doesnt show with spring-data-redis < 2.6.4 and spring boot = 2.5.14

**Comment by mp911de** [comment] 2022-09-19 14:15
Can you provide a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem?

**Comment by spring-projects-issues** [comment] 2022-09-26 14:20
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment] 2022-10-03 14:20
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-projects-issues** 2022-10-03 14:20 UTC
Labels: status: waiting-for-feedback, status: waiting-for-triage, status: feedback-reminder
