### ISSUE TITLE
Move CacheStatistics related classes to somewhere else, so it can be used for other cache implementations like custom ones

### ISSUE THREAD

**Issue by shahabkondri** [spring-projects/spring-data-redis#1984] opened 2021-02-25 17:13 UTC
Interfaces like `org.springframework.data.redis.cache.CacheStatistics` and `org.springframework.data.redis.cache.CacheStatisticsCollector` and `org.springframework.data.redis.cache.CacheStatisticsProvider` and the implementations of these interfaces do not have any dependency on Redis. They can be moved to another package like `org.springframework.cache` so custom cache implementations can use them to collect statistics.

**Comment by snicoll** [comment] 2021-02-25 18:18
I don't really understand what you're trying to do. I think it's quite hard to create an abstraction for cache statistics as you want to make sure to use as much metrics as you can and not being limited by things a particular cache does not support.

We won't be moving this to Spring Framework as it wouldn't make much sense to have an SPI that the framework itself wouldn't implement. Can you please explain how those classes would help you? What cache library are you targeting?

**Comment by shahabkondri** [comment] 2021-02-25 19:51
I added caching support for reactive type `Mono`, and for that, I created a ReactiveCache interface with two implementations `ReactiveRedisCache` and `ReactiveInMemoryCache`. 

As you might guess I am using `org.springframework.data.redis.cache.CacheStatistics` for `ReactiveRedisCache` implementation to collect metrics. I need to do the same and have statistics for `ReactiveInMemoryCache`, but since these cache implementations are in two different modules and packages and due to having CacheStatistics under redis package I can not re/use the same interfaces for `ReactiveInMemoryCache`.

**Comment by mp911de** [comment] 2021-02-26 07:11
`CacheStatistics` and the other interfaces serve the purpose of hiding the actual cache statistics implementation for Spring Data Redis and not pull in Micrometer as a dependency into Spring Data Redis. The design is specific to the Redis cache implementation. These types could have been classes if the cache stats had been mandatory by design. `CacheStatistics` are consumed by Spring Boot for integrating with Micrometer.

Since there's no general cache statistics abstraction in Spring and we do not intend to change our arrangement, we're closing this request as declined.

**Closed by mp911de** 2021-02-26 07:11 UTC
Labels: status: feedback-provided, status: waiting-for-triage
