### ISSUE TITLE
Spring's default TypeResolverBuilder creates a problem.

### ISSUE THREAD

**Issue by 2357457057** [spring-projects/spring-data-redis#2932] opened 2024-06-27 11:19 UTC
Here's a code example of the problem I ran into.
I use the RedisSerializer serialize a Object,but ican't deserialize it.
```java
  public static void main(String[] args) {
       GenericJackson2JsonRedisSerializer serializer = new GenericJackson2JsonRedisSerializer();
        serializer.configure(objectMapper -> objectMapper.registerModule(new JavaTimeModule()));

        String[] a = new String[]{"1", "2"};
        byte[] serialize = serializer.serialize(a);

        System.out.println(new String(serialize, StandardCharsets.UTF_8));
        try {
            System.out.println(serializer.deserialize(serialize));
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }

        //unmodifiableList
        List<String> collect = Arrays.stream(a).toList();
        serialize = serializer.serialize(collect);
        System.out.println(new String(serialize, StandardCharsets.UTF_8));
        try {
            System.out.println(serializer.deserialize(serialize));
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }

        //ArrayList
        collect = Arrays.stream(a).collect(Collectors.toList());
        serialize = serializer.serialize(collect);
        System.out.println(new String(serialize, StandardCharsets.UTF_8));
        try {
            System.out.println(serializer.deserialize(serialize));
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }
```

Executing the above code gives the following result:
1.  Array deserialization failed
2. unmodifiableList deserialization failed
3.  ArrayList was deserialized successfully

After debugging, I found that the code in the figure is causing this problem. It looks like it is filtering out some basic types, but why should it be written like this, so it is not causing some problems now? Can anyone help with that? Thank you very much

![image](https://github.com/spring-projects/spring-data-redis/assets/39323163/95fd51a6-22be-45fe-9608-1bd207048f97)

**Comment by mp911de** [comment] 2024-06-27 11:23
This is a duplicate of #2697

**Closed by mp911de** 2024-06-27 11:23 UTC
Labels: status: duplicate
