### ISSUE TITLE
Large number of RedisMessageListenerContainer threads

### ISSUE THREAD

**Issue by sm0217** [spring-projects/spring-data-redis#2358] opened 2022-07-07 14:22 UTC
Intermittently we see a huge spike in the number of RedisMessageListenerContainer threads created on default mapping expiry listener task executor blocked eventually bringing down the application. The async executor used does not have any upper limit on threads and I do not see a way to set a customised TaskExecutor for redis key value adapter (RedisMessageListenerContainer) which initialises the expiry listener. 

Only other way to stop this at the moment is to disable key space events but that will lead to indexes not cleaned up once the key expired. 

Any help on this please.

**Comment by mp911de** [comment] 2022-07-13 07:05
Closing as duplicate of #1827

**Closed by mp911de** 2022-07-13 07:05 UTC
Labels: status: duplicate
