### ISSUE TITLE
"READONLY You can't write against a read only replica" after restart redis docker containers with ansible playbook

### ISSUE THREAD

**Issue by jed1-ors** [spring-projects/spring-data-redis#2534] opened 2023-03-23 14:58 UTC
Hello. I use spring data redis starter and I have a problem with RedisSentinelConfiguration after failover due execute ansible playbook.

My microservice doesn't see master change after failover.
I have 3 replicas and 3 sentinels for each on the same hosts. In other words host1 with two ports, one for redis, another for sentinel and etc. (example, host1:6379,host1:26379; host2:6379,host2:26379; host3:6379,host3:26379)
When I execute the command "DEBUG SEGFAULT" or "DEBUG SLEEP 80" (for switch master testing), master change it role on slave and master switches, microservice track changes and take new master.
But when I run ansible playbook which contains follow tasks: stop redis container, stop sentinel container, some actions for configuration of redis and then start redis container, start redis sentinel container
Then problem is occur: io.lettuce.core.RedisReadOnlyException: READONLY You can't write against a read only replica

The main problem is MasterReplicaConnectionProvider.getConnectionAsync(WRITE) take old master for write operation. How to enforce MasterReplicaConnectionProvider update their knowNodes after full connectivity outage?

After restart of microservice the problem withdraws itself.

My config in redis starter below (Spring, Kotlin):

```
@Bean
fun lettuceClientOptionsBuilderCustomizer(): LettuceClientConfigurationBuilderCustomizer {
    return LettuceClientConfigurationBuilderCustomizer { builder ->
    	builder.readFrom(ReadFrom.REPLICA_PREFERRED) //enables SentinelConnector for MasterReplica API
            .clientOptions(ClientOptions.builder()
                .protocolVersion(ProtocolVersion.RESP3)
                .publishOnScheduler(true)
                .build())
            .useSsl()
            .disablePeerVerification()
    }
}

@Bean
fun redisSentinelConfiguration(properties: RedisProperties): RedisSentinelConfiguration {
    return RedisSentinelConfiguration(
        properties.sentinel!!.master ?: properties.defaults.sentinelMaster, //mymaster
        properties.sentinel.nodes //sentinelHost1:26379,sentinelHost2:26379,sentinelHost3:26379
    )
}
```

I tried to change configuration, but nothing help.
1) autoReconnect(true) for ClientOptions
2) validateConnection() for LettuceConnectionFactory

Help please. Any suggests will in help.

**Comment by mp911de** [comment] 2023-03-23 17:23
Duplicate of https://github.com/lettuce-io/lettuce-core/issues/2366

**Closed by mp911de** 2023-03-23 17:23 UTC
Labels: status: waiting-for-triage
