### ISSUE TITLE
SSubscribe support required for Redis sharded pub sub

### ISSUE THREAD

**Issue by gaurav-garg-jg** [spring-projects/spring-data-redis#3065] opened 2024-12-03 07:18 UTC
Description: The Pub/Sub mechanism needs to handle subscriptions across multiple shards. We are requesting support for SSubscribe, which would allow efficient and reliable subscribing to channels across Redis shards. This feature would ensure that messages are properly delivered across different Redis instances in a sharded setup, facilitating seamless communication across distributed systems.

Use Case: In scenarios where Redis is sharded for scalability or partitioning, subscribing to channels across shards becomes a challenge. The ability to use SSubscribe in such environments would simplify message distribution and consumption, improving performance and reliability for large-scale applications relying on Redis Pub/Sub for real-time messaging.

**Comment by mp911de** [comment] 2024-12-03 07:29
This is a duplicate of #3019.

**Closed by mp911de** 2024-12-03 07:29 UTC
Labels: status: duplicate
