### ISSUE TITLE
CrudRepository.findByIdOrNull() sometimes returns null even when there is a value

### ISSUE THREAD

**Issue by dlwhdals987** [spring-projects/spring-data-redis#2515] opened 2023-02-21 09:51 UTC
```gradle

val kotlinVer = "1.7.0"
id("org.springframework.boot") version "2.6.1"
id("io.spring.dependency-management") version "1.0.11.RELEASE"
```
```kt
@Repository
interface PlayerRepository : CrudRepository<Player, MemberId> {}
```

---------------------------------------------------------------------------------------
 **playerRepository.findByIdOrNull()** 
--> If you use it like the above, there will be cases where there is no data even if there is data

If there is a delay due to the large number of requests, sometimes the result is null.

Internally, it seems to use the `dispatch(<T> RedisCommand<K, V, T> dispatch(RedisCommand<K, V, T> command))` method in the  `io.lettuce.core.api.StatefulConnection.interface`. Is it related?

Is there a way to make the data reconciliation come out non-null?

**Comment by jxblum** [comment] 2023-02-23 04:48
Hi @dlwhdals987-

> DISCLAIMER:  I am no Redis expert and I am still learning the ins and outs of SD Redis as well as Redis.

Regarding:

> "_If there is a delay due to the large number of requests, sometimes the result is null._"

This is somewhat relevant to your ask (corrected & simplified):

> _Internally, it seems to use the `<T> AsyncCommand<K, V, T> dispatch(:RedisCommand<K, V, T>)` method in the io.lettuce.core.api.StatefulConnection.interface. Is it related?_

In short, yes.

However, let's be very clear here.

First you state, "_`playerRepository.findByIdOrNull(..)` will return no data even when data exists_", where the `PlayerRepository` extends the _Spring Data_ `CrudRepository` interface, where there is `findByIdOrNull(..)` method. So, I assume you actually mean the [`CrudRepository.findById(:ID):Optional<T>`](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html#findById(ID)) method, which returns an `Optional<Player>` in your case for a given`MemberId`, where you then access the requested `Player` as so:

```java
Player playerByMemberId = playerRepository.findById(memberId).orElse(null);
```

As you are probably already aware, _Spring Data Redis_ builds on _Spring Data KeyValue_, therefore SD Redis's (default) _Repository_ implementation is actually the SD KeyValue's `SimpleKeyValueRepository`.  Thus, when you invoke the `findById(:ID)` operation on the _Repository_, the following sequence of (~) calls will happen:

```txt
playerRepository.findById(memberId)
  -> SimpleKeyValueRepository.findById(memberId, Player.class):Optional<Player>
  -> SimpleKeyValueRepository.execute(:KeyValueAdapter):Optional<Player>
  -> RedisKeyValueAdapter.get(memberId, keyspace, Player.class) // a SD KeyValue KeyValueAdapter interface impl
  -> RedisTemplate.execute(:RedisConnection)
  -> DefaultedRedisConnection.hGetAll(key) // key is the memberId in binary form (byte[])
  -> LettuceHashCommands.hGetAll(key)
...
```

Now is the moment to pause and observe the [implementation](https://github.com/spring-projects/spring-data-redis/blob/3.0.2/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceHashCommands.java#L98-L104) of the `LuttuceHashCommand.hGetAll(key)` method. You will want to notice 2 things.

First, on [line 103](https://github.com/spring-projects/spring-data-redis/blob/3.0.2/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceHashCommands.java#L103), you will notice `connection.invoke()...`.  Inside`LettuceConnection`'s `invoke()` method ([here](https://github.com/spring-projects/spring-data-redis/blob/3.0.2/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnection.java#L745-L753)), this simply gets an "asynchronous" connection.

Second, this actually corresponds to the fact that on [line 103](https://github.com/spring-projects/spring-data-redis/blob/3.0.2/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceHashCommands.java#L103), the `RedisHashAsyncCommands::hgetall` "asynhronous" operation (command) will invoked using the "asynchronous" connection. Inside `RedisHashAsyncCommands.hGetAll(..)` is where we find the `dispatch(..)` method invocation to which you are referring.

The `connetion.invoke()` method returns a SD Redis `LettuceInvoker` instance, where the `just(..)` method will be called with the command to execute (invoke asynchronously). As you can see, this uses a `Synchronizer`, [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.2/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceInvoker.java#L94) to invoke (and handle) our (asynchronous) command (i.e. `RedisHashAsycnCommands.hGetAll(..)`).

The `Synchronizer` implementation was provided by the `LettuceConnection` back in the `doInvoke(..)` method, [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.2/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnection.java#L778-L829). It is the 2nd argument to the `LettuceInvoker` constructor, with conditional construction based on whether we [opened a pipeline](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/connection/lettuce/LettuceConnection.html#openPipeline()),  are [inside a transaction](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/connection/lettuce/LettuceConnection.html#multi()), or we are simply executing the command and wish to "wait" for the result, [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.2/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnection.java#L814-L828), and specifically [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.2/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnection.java#L818), then [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.2/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnection.java#L951-L963).

Let's assume you are using the normal execution path (i.e. not in pipeline or transaction (referred to as `isQueueing()` or `isMulti` by the `LettuceConnection`). Then the _Lettuce_ driver provides a means to handle the `RedisFuture` using a **timeout** ([here](https://github.com/spring-projects/spring-data-redis/blob/3.0.2/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnection.java#L959)) that you configure on the connection, and in this case, the `LettuceConnection`.

SOLUTION:

I think you can configure the `timeout` for operations on the `LettuceConnection` using the `LettuceConnectionFactory`.

For example:

```java
@Configuration
class ApplicationRedisConfiguration {

  @Bean
  LettuceConnectionFactory redisConnectionFactory() {

    return new LettuceConnectionFactory(<redisConfigurationImpl>, LettuceClientConfiguration.builder()
      .commandTimeout(Duration.ofSeconds(30L));
  }
}
```

The `<redisConfigurationImpl>` could be any of [ `RedisConfiguration`, 'RedisClusterConfiguration`, 'RedisSentinelConfiguration`, `RedisStandaloneConfiguration` ] depending on your topology arrangement. See LettuceConnectionFactory constructors in [Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/connection/lettuce/LettuceConnectionFactory.html).

See the `LettuceClientConfiguration` [Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/connection/lettuce/LettuceClientConfiguration.html) for more details.

Based on the [source](https://github.com/spring-projects/spring-data-redis/blob/3.0.2/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceClientConfiguration.java#L195-L197) of the `LettuceClientConfiguration`, it also appears that the timeout can be possibly configured in the Lettuce `RedisURI` (i.e. the connection URL used to connect to your Redis server(s)/cluster) as well.  So you might want to double check how this is configured in your respective environments (DEV, TEST, PROD) as you may not see the same behavior in different environments since the configuration might vary significantly.

In summary...

Although, I am not 100% certain, I think you might be seeing `null` returns values when the server is loaded because 1) the operations/commands inside SD Redis are executed "asynchronously" with the Lettuce driver and 2) the operation is timing out when the servers are loaded (due to a large number of requests). Therefore, I think you need to tune your connection and possibly your servers in this case.

Hope this helps. Cheers!

**Comment by jxblum** [comment] 2023-02-23 04:58
Regarding the `CrudRepository.findByOrNull(..)` method... you are CORRECT (or rather, I stand corrected) since our _**Kotlin**_ support in _Spring Data Commons_ does include such a [method](https://github.com/spring-projects/spring-data-commons/blob/2.6.1/src/main/kotlin/org/springframework/data/repository/CrudRepositoryExtensions.kt#L26).

And, of course, in [your Issue description](https://github.com/spring-projects/spring-data-redis/issues/2515#issue-1593162870) you not only referred to the use of _**Kotlin**_ in your build/dependency declarations and configuration, but also in syntax.

My apologies.

**Comment by Hwan-seok** [comment] 2023-02-23 06:46
Hi @jxblum! Thanks for the answer 😄

Seems the default command timeout is 60 seconds based on [here](https://github.com/spring-projects/spring-data-redis/blob/9ce1e37176d5efa0f34d4676a0bbcf642ae103b9/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnectionFactory.java#L1424).
So I don't understand that changing command timeout from 60s to 30s makes different in this situation?

**Comment by mp911de** [comment] 2023-02-23 07:52
> If you use it like the above, there will be cases where there is no data even if there is data

It would be good for us if you could provide us with a minimal reproducer along with either an `rdb` file or a redis script to populate the redis data so we can investigate at which point a mismatch happens. Alternatively, you now have guidance in terms of invoked methods that you could debug yourself.

> The asynchronous invocation of Redis commands inside SD Redis is not something that is likely to change either.

Lettuce uses an event-loop based I/O approach as general mode of operation. The synchronous/asynchronous/reactive APIs are merely a facade towards on top of the event loop. We simplified the design of using Lettuce over the years from mixed sync/async towards using the asynchronous API only. Previously, when we used the synchronous API, Lettuce enforced the synchronization timeout. Now Spring Data Redis applies the command timeout to the `RedisFuture` when waiting for a result.

**Comment by jxblum** [comment] 2023-02-23 19:11
Hi @Hwan-seok -

Regarding...

> _Seems the default command timeout is 60 seconds based on [here](https://github.com/spring-projects/spring-data-redis/blob/9ce1e37176d5efa0f34d4676a0bbcf642ae103b9/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnectionFactory.java#L1424). So I don't understand that changing command timeout from 60s to 30s makes different in this situation._

When I traced through the code I did not look at the initial configuration of the command timeout (i.e. 60 seconds).

Also, in my example, I arbitrarily picked 30 seconds since 1) I figured the actual command timeout used by Redis client drivers (e.g. Lettuce or Jedis) would be much less and 2) 30 seconds typically corresponds to many request timeouts used in other systems of communication.

Sorry for the confusion.

Additionally, I also think it is important to look at your use case(s) and requirements (even SLAs) and tune the system (clients and servers) accordingly. At the risk of stating obvious, there is no 1 size fits all in every case. You have to balance load with responsiveness in the application. Too long of a timeout and users are going to be impacted. Too short of a timeout and the application will need to adjust in flight. Either way, it requires work on the application/system and critical design choices need to be made.

Finally, I am still reasonably confident that, given the asynchronous nature of the Redis command execution (as @mp911de more accurately described above), execution of the Redis command in certain instances is taking longer than expected and the `RedisFuture` does not yet contain a value. It really is no different than Java's [`Future.get(timeout, :TimeUnit)`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Future.html#get-long-java.util.concurrent.TimeUnit-) operation that returns the asynchronous computed result "**if available**".

1 more thing...

Arguably, the `RedisFuture.await(..)` call in the stack I demonstrated above could 1) throw a (configurable)`TimeoutException` like `Future.get(..)` or 2) the call could simply be replaced with `RedisFuture.get(timeout, :TimeUnit)` in SD Redis's `LettuceConnection` (perhaps). Since `RedisFuture` already extends `Future` then I would not change the contract of `await`, personally.

**Comment by Hwan-seok** [comment] 2023-02-25 19:15
Thanks for very detailed explanation @mp911de, @jxblum !
The reason why I couldn't provide a minimal reproducible example is it didn't really occur when I tried to reproduce it only using `findByIdOrNull()`.

**But I managed to find out it is because of a combination of `findByIdOrNull()` and the `save()`.**

The `save()` method internally uses the [put](https://github.com/spring-projects/spring-data-redis/blob/9ce1e37176d5efa0f34d4676a0bbcf642ae103b9/src/main/java/org/springframework/data/redis/core/RedisKeyValueAdapter.java#L191) and it first dispatches the `del` command and then re-set it by `hmset` then finally updates its indexes.
Theses sequence of commands is not tied up to the multi or a transaction. So it is not safe in the race condition.
Let's assume dispatching the command `hmget`(findByIdOrNull) in the middle of the`del` and `hmset`(save). It may return null.

Sorry for the confusion.

Maybe the `save()` has these commands by design so I assume it's normal behavior. But IMHO, it would be better if they are tied up with like multi or something so that we can confirm that it is thread-safe.
What do you think?

**Comment by jxblum** [comment] 2023-03-03 00:22
Hi @Hwan-seok -

I apologize for the lapse in communication; I got tangled up in other things.

First, thank you for sharing your findings and clarifying the technical details in your use case. This makes more sense. So, let's dig in.

Regarding...

> _Maybe the save() has these commands by design so I assume this issue is not a bug but normal behavior. _

Again, I am no Redis expert (I have much to learn yet), and the code in SD Redis was written well before my time, but after careful review and consideration, I do think the sequence of Redis commands in the [`RedisKeyValue.put(..)`](https://github.com/spring-projects/spring-data-redis/blob/3.0.2/src/main/java/org/springframework/data/redis/core/RedisKeyValueAdapter.java#L210-L248) operation used by _CrudRepository_ `save(..)` was definitely deliberate and by design.

Although, I am not 100% certain that every Redis command, like `DEL` in the `put` operation, was necessary in this case (particularly given the [`HSET` command](https://redis.io/commands/hset/), or rather the now deprecated, but still used [`HMSET` command](https://redis.io/commands/hmset/), "overwrites" the data), it also seems to me that the sequence of commands in `put`, or even if `put` were implemented as only a single command (e.g. just `HSET`), would not matter anyway. 

> NOTE: Minimally, it seems logical to me the object would need to be 1) updated (saved) at the very least (obviously) 2) eviction triggered (possibly necessary for some notifications, such as [SD Events](https://docs.spring.io/spring-data/commons/docs/current/reference/html/#core.domain-events)? or session management) and 3) updating the index on the data (structure) to access the updated object efficiently.

Referring back to something @mp911de stated above in his [comment](https://github.com/spring-projects/spring-data-redis/issues/2515#issuecomment-1441326510), "_**Lettuce uses an event-loop based I/O approach** as general mode of operation. The synchronous/asynchronous/reactive APIs are merely a facade on top of the event loop. We simplified the design of using Lettuce over the years from mixed sync/async towards **using the asynchronous API only**._"

This means anytime you have _compound actions_ (in the same call or across calls) that are **not** atomic, there is always the possibility for a _race condition_. 

So, even if the `put` operation consisted only of the `HSET` command and your application immediately followed the call to _Repository_ `save(..)` with _Repository_ `findByIdOrNull(..)`, AND even if your application (or test) were to perform both  _Repository_ operations in the same Thread, it is still possible to get `null` values because, the fact of the matter is, there will always be multiple Threads involved between the 2 _Repository_ operations (since _Lettuce_ uses asynchronous invocations for each `HSET` (in `save(..)`) and `HGETALL` (in `findByIdOrNull(..)`) and technically you don't know whether the `save(..)` (`HSET`) succeeded until the client receives and ACK from the server, which is wrapped in an async call.

Therefore, the following sequence of ops (and associated commands) can still fail even when performed by the same Thread: `save(..)`/async `HSET` followed by `findByIdOrNull(..)`/ async`HGET`.

This would absolutely need to happen to get a non-`null` response: `save(..)`/async `HSET`, client receives ACK from server for `HSET`, then `findByIdOrNull(..)`/async `HGET`.

Even then (with an ACK), there is still a possibility of a `null` return value if you think about from a clustered Redis topology context, where the read could come from a Replica. The replication of the value between masters and replicas in Redis is (always?) asynchronous. So, whether single-Threaded or multi-Threaded/multiple processes (multiple instances of your application) is involved, the problem could still manifest itself.

Regarding...

> _it would be better if they are tied up with like multi or something so that we can confirm that it is thread-safe_

Initiating a transaction isn't necessary in every use case and will cause additional overhead and latency in use cases where more stringent consistency guarantees are not required. You can certainly do so though by simply enabling and using Spring's Transaction Management infrastructure and support with SD Redis (see [here](https://docs.spring.io/spring-data/redis/docs/current/reference/html/#tx)).

However, the point I was trying to make above is that it is not going to be Thread-safe given the async nature of the command execution, as applied by _Lettuce_ anyway (I am not certain about Jedis), particularly without coordination (like Transactions), which should be an opt-in approach given it is highly application requirement dependent.

Other things to consider or try (and food for thought)...

1) I am not sure if _pipelining_ would help much in this case. I kind of doubt it, but it came to mind as I was reviewing the code.

2) You still have to be very much cognizant of a clustered Redis deployment and the (configurable?) asynchronous replication between nodes (Redis servers), and where read operations (can) originate, which might have an affinity based on locality.

3) What happens with Jedis in this scenario I wonder?

4) There may be other applicable configuration options to consider, and tuning plays a big role particularly when given different loads (at different times) in different server/cluster topology arrangements, and so on and on. You have to carefully consider PROD since your DEV environment probably looks nothing like PROD, too.

5) Test the use of Spring's Transaction Management here. I think this should prove invaluable, maybe in this particular use case, or you application at large, particularly if consistency is important. But, remember...

6) (As I am certain you are well aware), Redis is an eventually consistent system by design and Redis does not offer strong consistency guarantees, particularly in a cluster topology arrangement (see [here](https://redis.io/docs/management/scaling/), and search for "_Redis Cluster consistency guarantees_").

7) ???

Given there is no one size fits all in this case, and a lot has to do with the driver (Lettuce) you chose in this case, I am not inclined to say anything is necessarily wrong with Spring Data Redis (and it's Repository infrastructure) extensions in this case.

I hope I made sense.

**Comment by jxblum** [comment] 2023-03-03 00:54
This may have boiled down to a philosophical discussion, and given my lack of experience with Redis, I am not sure I am being that helpful or can offer any additional insights into this case. Hopefully, I have given you something to think about.

In any case, I don't think this will lead to changes in Spring Data Redis ATM given I am not convinced Spring Data Redis is necessarily doing anything wrong by design. I also feel like there are options (e.g. using transactions) in this case.

I am always open to receiving any additional feedback. (This has been a great learning opportunity for me).

Thank you.

**Comment by Hwan-seok** [comment] 2023-03-05 19:13
Thanks for the detailed response again @jxblum 😄 
> Me neither an expert on the SD nor a Redis. You must be way more expert than me.

I agree with what you mentioned:
> consisted only of the HSET command and your application immediately followed the call to Repository save(..) with Repository findByIdOrNull(..), AND even if your application (or test) were to perform both Repository operations in the same Thread, it is still possible to get null

---
> Although, I am not 100% certain that every Redis command, like DEL in the put operation, was necessary in this case (particularly given the [HSET command](https://redis.io/commands/hset/), or rather the now deprecated, but still used [HMSET command](https://redis.io/commands/hmset/), "overwrites" the data), it also seems to me that the sequence of commands in put, or even if put were implemented as only a single command (e.g. just HSET), would not matter anyway.

> I also don't think SD Redis Repository impl is smart in that it only updates fields in the hash identified by the key (entity ID) for properties/fields (state) in the object that changed. I could be wrong, but I don't believe so.

Totally agree at least IMHO. But neither `HSET` nor `HMSET` does not overwrite entire hashes but only `upserts`. So probably the `del` in the save seems inevitable.

Also, I have some thoughts which are almost same aligned with the above:

In any environment such as with a different replica or driver, FWIW, let's define the case that a hash was already been set. It's natural that `save()` and `findByIdOrNull()` can be racing toward the hash but in my humble opinion, `findByIdOrNull()` should at least give a previous value.
Imagine the following sequence of operations and let's say `save(2)` and `findByIdOrNull()` is fired at a similar point in the timeline. 
```
Thread 1: save(1)---done(1)---save(2)
Thread 2: ---------------------findByIdOrNull()
```
In this race condition, I don't expect the result of `findByIdOrNull()` to be 2. But at least 1 or 2. Not `null`. 
But it can be `null` in the current implementation because it deletes the has completely and then re-sets it.

But I don't think there is an operation that overwrites the entire hash. It's only for individual fields.
Also, the SD Redis cannot easily compare current fields with updating fields locally because there are distributed applications that are using SD Redis and those entities are different in each application. And I assume that `save()` means "Hey, I don't care what state of actual current value but overwrite by this value!".
So the conclusion is.. it could be done by... yes, putting them in the transition`(MULTI)`. But It should be done by users.

Anyway, thanks for your kind help in figuring out this 😃

**Comment by jxblum** [comment] 2023-03-06 23:12
Hi @Hwan-seok -

Regarding the scenario you nicely demonstrated:

```
Thread 1: save(1) --- done(1) --- save(2)
Thread 2: ------------------------findByIdOrNull()
```

... expecting to see the previous value (1) from the first (completed) `save(1)` before the call to `findByIdOrNull(..)`, particularly if the second `save(2)` has not completed yet (i.e. is "**in the middle**") or threw an Exception ... is a great point!

Given the current implementation of _KeyValueRepository_ `save(..)` in SD Redis, without transactions, another Thread calling `findByIdOrNull(..)` can definitely witness _in-flight_ operations given `save(..)` executes (minimally) 3 separate Redis commands in the implementation. And, we have come full circle.

So, I agree with:

> _So the conclusion is.. it could be done by... yes, putting them in the transition(MULTI). But It should be done by users._

Correct!

And, a transaction can be initiated when entering a Spring's `@Transactional` annotated application service/DAO method or programmatically using Spring's `TransactionTemplate`. Either way, any Thread, or even another process in a distributed application using Redis cluster topology should minimally see the previous value (i.e. "1" from `save(1)` in the scenario you demonstrated above).

I stand corrected on the [`hset`](https://redis.io/commands/hset/) Redis command (or `hmset` for that matter). Indeed, it only takes fields/values of the hash, so deleting the previous entry is required given SD Redis has no means of tracking what state in the object that is subject to the `save(..)` has changed.

You are welcome for the help. I really appreciated and enjoyed our conversation.

Good luck!

**Comment by jxblum** [comment] 2023-03-07 01:35
Hi @Hwan-seok -

I was just thinking about 1 more thing I remembered seeing in the execution path of _Repository_ `save(..)` that I wanted to call to your attention; [this](https://github.com/spring-projects/spring-data-redis/blob/2.7.9/src/main/java/org/springframework/data/redis/core/RedisKeyValueAdapter.java#L247-L259). The [(end-of-line) comment](https://github.com/spring-projects/spring-data-redis/blob/2.7.9/src/main/java/org/springframework/data/redis/core/RedisKeyValueAdapter.java#L247) makes it sound like, if the operation were to fail, then you would at least see the previous value (stored under a "phantom key") once restored.

I am not sure if this is something SD Redis is doing (possibly; see note below) or Redis itself, but [appears](https://github.com/spring-projects/spring-data-redis/blob/2.7.9/src/main/java/org/springframework/data/redis/core/RedisKeyValueAdapter.java#L247) to be enabled with configuration (i.e. `keepShadowCopy()`).

> NOTE: _I don't recall seeing a shadow copy (of the value?) being made, stored under a phantom key, during `save(..)`, before the `put(..)` operation in `RedisKeyValueAdapter`. I am not even certain what this [block](https://github.com/spring-projects/spring-data-redis/blob/2.7.9/src/main/java/org/springframework/data/redis/core/RedisKeyValueAdapter.java#L247-L259) is attempting to do, actually. I will need to get some guidance from team (@mp911de or @christophstrobl) on this one.

I have also not tested my claim above, so I am not certain I am even correct about restoration of the previous value before the attempted `save(..)`.

However, 1 thing is for certain, either way, it definitely won't solve the race-condition in a multi-Threaded context either, as I am sure you are quite aware.

**Comment by Hwan-seok** [comment] 2023-03-07 02:55
Due to the lack of my understanding, I couldn't find any restoration process related to phantom keys 😅.  Perhaps another part of the SD Redis seems using them?

Indeed. 
> All I know is, it does seem dangerous if a del can happen without some form of restore if hset were to fail all because save(..) uses multiple Redis commands (a recipe for data loss in this scenario).

Even though this could be directly related to a race condition, it could be another issue if there is no process to restore deleted values.

As you mentioned, although, the phantom key does not help with a race condition 🤣 
> However, 1 thing is for certain, either way, it definitely won't solve the race-condition in a multi-Threaded context either, as I am sure you are quite aware.

**Comment by jxblum** [comment] 2023-03-08 00:43
Hi @Hwan-seok -

I was doing more digging ("research", 😄 ) on this issue today and came across this [source](https://github.com/spring-projects/spring-data-redis/blob/3.0.3/src/main/java/org/springframework/data/redis/core/RedisKeyValueAdapter.java#L399-L476) in SD Redis.

Essentially, if your application domain model object (entity) extends the `PartialUpdate` class ([Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/PartialUpdate.html)), then SD Redis will update the associated Redis hash for only the properties of the entity that have changed.

This should be the effect of the `RedisKeyValueAdapter.update(..)` method, [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.3/src/main/java/org/springframework/data/redis/core/RedisKeyValueAdapter.java#L443-L448). The `rdo.getBucket().rawMap()` method should return a `Map` of only field/values (properties) of the entity that have actually changed, passed to the `hset` command, thereby updating the Redis hash identified by key (keyspace-based entity ID) for the entity. The RDO (`RedisData` object) is [created](https://github.com/spring-projects/spring-data-redis/blob/3.0.3/src/main/java/org/springframework/data/redis/core/RedisKeyValueAdapter.java#L409-L410) (and initialized) from the `PartialUpdate` object passed to `update(..)`.

> NOTE: _This is in contrast to the `RedisKeyValueAdapter.put(..)` operation ([here](https://github.com/spring-projects/spring-data-redis/blob/3.0.3/src/main/java/org/springframework/data/redis/core/RedisKeyValueAdapter.java#L191-L196)) that constructs/intializes a `RedisData` object (RDO) from the entire object (entity) being saved._

In addition, there is no prior `del` command being issued in the `RedisKeyValueAdapter.update(..)` method to clear the state of the object/entity from the Redis hash prior to saving the changed/updated object/entity.

Furthermore, this should also eliminate any _data loss_ as well as the strict need for wrapping _Repository_ operations, such as `save(..)` and `findByIdOrNull(..)`, in a transaction (which SD Redis implements with the `MULTI` command followed by either `EXEC` or `DISCARD`), unless strict consistency and durability/reliability are required.

Unfortunately, SD Redis's _Repository_ `save(..)` method is NOT implemented to take partial updates into consideration. 😞

> NOTE: _On the flip side, an unfortunate side effect of using partial updates is having to extend SD Redis's `PartialUpdate` class in your application domain model class, coupling your application to SD Redis._

If we trace this through, we'd see that SD Redis's _Repository_ extension primary builds on SD KeyValue's base _Repository_ infrastructure. That is, `RedisRepositoryFactory` [extends](https://github.com/spring-projects/spring-data-redis/blob/3.0.3/src/main/java/org/springframework/data/redis/repository/support/RedisRepositoryFactory.java#L43) `KeyValueRepositoryFactory`. Therefore, the implementation of the application declared _Repository_ interface would be backed by `SimpleKeyValueRepository` ([here](https://github.com/spring-projects/spring-data-keyvalue/blob/3.0.3/src/main/java/org/springframework/data/keyvalue/repository/support/KeyValueRepositoryFactory.java#L128-L131)).

> NOTE: Most Spring Data modules, such as SD MongoDB, either 1) don't build on the [SD KeyValue module](https://github.com/spring-projects/spring-data-keyvalue#spring-data-keyvalue--), or 2) will _override_ the `getRepositoryBaseClass(:RepositoryMetadata)` method and return a store-specific implementation (for [example](https://github.com/spring-projects/spring-data-mongodb/blob/4.0.3/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/repository/support/MongoRepositoryFactory.java#L85-L88)).

> NOTE: Of course, SD KeyValue contains a nice foundation for key/value stores, like Redis (_Hazelcast_ (AFAIR) extends SD KeyValue as well), and most of the implementation details are encapsulated in, and delegated to, the `KeyValueAdapter` implementation ([Javadoc](https://javadoc.io/static/org.springframework.data/spring-data-keyvalue/3.0.3/org/springframework/data/keyvalue/core/KeyValueAdapter.html)), which in SD Redis, is the `RedisKeyValueAdapter` ([Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/RedisKeyValueAdapter.html)), which has been the primary focus of our conversation.

SD KeyValue's `SimpleKeyValueRepository.save(..)` method ([source](https://github.com/spring-projects/spring-data-keyvalue/blob/3.0.3/src/main/java/org/springframework/data/keyvalue/repository/support/SimpleKeyValueRepository.java#L67-L77)) calls the `KeyValueOperations.update(ID, <entity of type T>)` method ([here](https://github.com/spring-projects/spring-data-keyvalue/blob/3.0.3/src/main/java/org/springframework/data/keyvalue/repository/support/SimpleKeyValueRepository.java#L76)) directly.

If `save(..)` had rather called `KeyValueOperations.update(<entity of type T>)` ([Javadoc](https://javadoc.io/static/org.springframework.data/spring-data-keyvalue/3.0.3/org/springframework/data/keyvalue/core/KeyValueOperations.html#update(T))) instead, the outcome would be different. This is because SD Redis's implementation of the SD KeyValue `KeyValueOperations` interface is `RedisKeyValueTemplate` ([Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/RedisKeyValueTemplate.html)). And, if we look at the `update(<entity of type T>)` method implementation, we [see](https://github.com/spring-projects/spring-data-redis/blob/3.0.3/src/main/java/org/springframework/data/redis/core/RedisKeyValueTemplate.java#L152-L162) that it would handle "partial updates" by calling the `RedisKeyValueAdapter.update(:PartialUpdate)` method ([source](https://github.com/spring-projects/spring-data-redis/blob/3.0.3/src/main/java/org/springframework/data/redis/core/RedisKeyValueTemplate.java#L173-L176)).

However, and again, since `SimpleKeyValueRepository.save(..)` called the `KeyValueOpertions.update(ID, <entity of type T>)` method directly ([source](https://github.com/spring-projects/spring-data-keyvalue/blob/3.0.3/src/main/java/org/springframework/data/keyvalue/repository/support/SimpleKeyValueRepository.java#L76)), `RedisKeyValueAdapter` simply passes the call through ([source](https://github.com/spring-projects/spring-data-redis/blob/3.0.3/src/main/java/org/springframework/data/redis/core/RedisKeyValueTemplate.java#L164-L167)) to the default implementation provided in SD KeyValue's `KeyValueTemplate` ([source](https://github.com/spring-projects/spring-data-keyvalue/blob/3.0.3/src/main/java/org/springframework/data/keyvalue/core/KeyValueTemplate.java#L191-L207)), which would just call the `[Redis]KeyValueAdapter.put(..)` method, [here](https://github.com/spring-projects/spring-data-keyvalue/blob/3.0.3/src/main/java/org/springframework/data/keyvalue/core/KeyValueTemplate.java#L201) bypassing the partial update.

I am not convinced this was by design.

**Comment by jxblum** [comment] 2023-03-08 01:09
@mp911de & @christophstrobl -

After a complete and thorough analysis of this issue, I am convinced that either:

1) SD KeyValue's `SimpleKeyValueRepository.save(..)` method ([source](https://github.com/spring-projects/spring-data-keyvalue/blob/3.0.3/src/main/java/org/springframework/data/keyvalue/repository/support/SimpleKeyValueRepository.java#L67-L77)) is [calling](https://github.com/spring-projects/spring-data-keyvalue/blob/3.0.3/src/main/java/org/springframework/data/keyvalue/repository/support/SimpleKeyValueRepository.java#L76) the wrong `KeyValueOperations.update(..)` method ([Javadoc](https://javadoc.io/doc/org.springframework.data/spring-data-keyvalue/latest/org/springframework/data/keyvalue/core/KeyValueOperations.html)), that is [`update(ID, <entity of type T>)`](https://javadoc.io/static/org.springframework.data/spring-data-keyvalue/3.0.3/org/springframework/data/keyvalue/core/KeyValueOperations.html#update(java.lang.Object,T)) rather than, and more appropriately, [`update(<entity of type T>)`](https://javadoc.io/static/org.springframework.data/spring-data-keyvalue/3.0.3/org/springframework/data/keyvalue/core/KeyValueOperations.html#update(T)), or...

2) SD Redis should provide a custom extension of SD KeyValue's `SimpleKeyValueRepository` class, overriding the `save(..)` method to call the appropriate `KeyValueOperations.update(..)` method, thereby enabling partial updates to be considered.

> NOTE: See  my [comment](https://github.com/spring-projects/spring-data-redis/issues/2515#issuecomment-1459091436) above for complete details.

If we were to change SD KeyValue's `SimpleKeyValueRepository.save(..)` method to instead call `KeyValueOperations.update(<entity of type T>)`, it would still 1) ultimately [call](https://github.com/spring-projects/spring-data-keyvalue/blob/3.0.3/src/main/java/org/springframework/data/keyvalue/core/KeyValueTemplate.java#L188) `KeyValueOerations.update(ID, <entity of type T>)`, resolving the ID in similar manner as [before]([url](url)), and 2) allow SD KeyValue module extensions, like SD Redis, to override and customize the default behavior to handle special concerns, like [partial updates in the case of Redis](https://github.com/spring-projects/spring-data-redis/blob/3.0.3/src/main/java/org/springframework/data/redis/core/RedisKeyValueTemplate.java#L152-L162).

Additionally, this would keep all SD KeyValue module extensions consistent in behavior.

However, in fear of adversely affecting SD modules that do extend from SD KeyValue, then option #2 presented above could be the alternatively. Although, to my knowledge, only SD Redis and SD Hazelcast extend from SD KeyValue AFAIK.

While this does not eliminate all possible _race conditions_, I do think it would solve the `null` intermediate values _race condition_ and prevent _data loss_.

Again, I would encourage users that require strict consistency along with durability and reliability to use transactions in this case. Still, I think there is room for improvement.

WDYT?

**Comment by jxblum** [comment] 2023-05-08 18:35
Per the discussion above, the SD Redis _Repository_ `save(..)` method is by design, using the `DEL` command followed by the `HMSET` command.

There is no guarantee, especially in multi-Threaded or distributed/clustered environment that this operation will be atomic, unless the user opts to use (Redis) Transactions, which are supported by Spring Data Redis using core Spring Framework Transaction Management infrastructure. More information on using Redis Transaction in a Spring context can be found in the SD Redis ref doc, [here](https://docs.spring.io/spring-data/redis/docs/current/reference/html/#tx).

Given there is not further activity on this Issue ticket, and SD Redis functions as designed, I am closing this ticket.

**Closed by jxblum** 2023-05-08 18:35 UTC
Labels: in: lettuce, in: repository, status: feedback-provided
